// Second batch of names to reach 2000+
const fs = require('fs');
const path = require('path');

const moreGirlNames = [
  { name: 'Magnolia', slug: 'magnolia', gender: 'girl', origin: 'Latin', meaning: 'Flower named after botanist', popularity: 185 },
  { name: 'Mabel', slug: 'mabel', gender: 'girl', origin: 'Latin', meaning: 'Lovable', popularity: 285 },
  { name: 'Madeleine', slug: 'madeleine', gender: 'girl', origin: 'French', meaning: 'High tower', popularity: 385 },
  { name: 'Maren', slug: 'maren', gender: 'girl', origin: 'Latin', meaning: 'Sea', popularity: 345 },
  { name: 'Marianna', slug: 'marianna', gender: 'girl', origin: 'Latin', meaning: 'Of the sea', popularity: 398 },
  { name: 'Marissa', slug: 'marissa', gender: 'girl', origin: 'Latin', meaning: 'Of the sea', popularity: 398 },
  { name: 'Marlene', slug: 'marlene', gender: 'girl', origin: 'German', meaning: 'Star of the sea', popularity: 512 },
  { name: 'Martha', slug: 'martha', gender: 'girl', origin: 'Aramaic', meaning: 'Lady', popularity: 485 },
  { name: 'Maxine', slug: 'maxine', gender: 'girl', origin: 'Latin', meaning: 'Greatest', popularity: 485 },
  { name: 'Meadow', slug: 'meadow', gender: 'girl', origin: 'English', meaning: 'Field of grass', popularity: 345 },
  { name: 'Meredith', slug: 'meredith', gender: 'girl', origin: 'Welsh', meaning: 'Great ruler', popularity: 398 },
  { name: 'Mikayla', slug: 'mikayla', gender: 'girl', origin: 'Hebrew', meaning: 'Who is like God', popularity: 285 },
  { name: 'Milan', slug: 'milan-girl', gender: 'girl', origin: 'Slavic', meaning: 'Gracious, dear', popularity: 345 },
  { name: 'Milena', slug: 'milena', gender: 'girl', origin: 'Slavic', meaning: 'Gracious', popularity: 398 },
  { name: 'Mina', slug: 'mina', gender: 'girl', origin: 'German', meaning: 'Love', popularity: 398 },
  { name: 'Miracle', slug: 'miracle', gender: 'girl', origin: 'English', meaning: 'Wonder', popularity: 365 },
  { name: 'Monroe', slug: 'monroe', gender: 'girl', origin: 'Scottish', meaning: 'Mouth of the Roe river', popularity: 285 },
  { name: 'Myra', slug: 'myra', gender: 'girl', origin: 'Latin', meaning: 'Admirable', popularity: 425 },
  { name: 'Myla', slug: 'myla', gender: 'girl', origin: 'English', meaning: 'Merciful', popularity: 225 },
  { name: 'Nadia', slug: 'nadia', gender: 'girl', origin: 'Slavic', meaning: 'Hope', popularity: 288 },
  { name: 'Nancy', slug: 'nancy', gender: 'girl', origin: 'Hebrew', meaning: 'Grace', popularity: 512 },
  { name: 'Nathalie', slug: 'nathalie', gender: 'girl', origin: 'French', meaning: 'Birthday of the Lord', popularity: 485 },
  { name: 'Nella', slug: 'nella', gender: 'girl', origin: 'Greek', meaning: 'Light', popularity: 512 },
  { name: 'Nellie', slug: 'nellie', gender: 'girl', origin: 'English', meaning: 'Light', popularity: 398 },
  { name: 'Nia', slug: 'nia', gender: 'girl', origin: 'Welsh', meaning: 'Purpose', popularity: 325 },
  { name: 'Noelle', slug: 'noelle', gender: 'girl', origin: 'French', meaning: 'Christmas', popularity: 185 },
  { name: 'Noemi', slug: 'noemi', gender: 'girl', origin: 'Hebrew', meaning: 'Pleasantness', popularity: 345 },
  { name: 'Noor', slug: 'noor', gender: 'girl', origin: 'Arabic', meaning: 'Light', popularity: 485 },
  { name: 'Oaklyn', slug: 'oaklyn', gender: 'girl', origin: 'English', meaning: 'Oak tree lake', popularity: 285 },
  { name: 'Octavia', slug: 'octavia', gender: 'girl', origin: 'Latin', meaning: 'Eighth', popularity: 365 },
  { name: 'Opal', slug: 'opal', gender: 'girl', origin: 'Sanskrit', meaning: 'Jewel', popularity: 485 },
  { name: 'Paola', slug: 'paola', gender: 'girl', origin: 'Italian', meaning: 'Small', popularity: 398 },
  { name: 'Patience', slug: 'patience', gender: 'girl', origin: 'English', meaning: 'Endurance', popularity: 485 },
  { name: 'Paula', slug: 'paula', gender: 'girl', origin: 'Latin', meaning: 'Small', popularity: 512 },
  { name: 'Pearl', slug: 'pearl', gender: 'girl', origin: 'English', meaning: 'Pearl gemstone', popularity: 425 },
  { name: 'Penny', slug: 'penny', gender: 'girl', origin: 'Greek', meaning: 'Weaver', popularity: 398 },
  { name: 'Perla', slug: 'perla', gender: 'girl', origin: 'Spanish', meaning: 'Pearl', popularity: 425 },
  { name: 'Petra', slug: 'petra', gender: 'girl', origin: 'Greek', meaning: 'Rock', popularity: 512 },
  { name: 'Poppy', slug: 'poppy', gender: 'girl', origin: 'Latin', meaning: 'Red flower', popularity: 285 },
  { name: 'Priscilla', slug: 'priscilla', gender: 'girl', origin: 'Latin', meaning: 'Ancient', popularity: 485 },
  { name: 'Promise', slug: 'promise', gender: 'girl', origin: 'English', meaning: 'Pledge', popularity: 425 },
  { name: 'Raegan', slug: 'raegan', gender: 'girl', origin: 'Irish', meaning: 'Little king', popularity: 285 },
  { name: 'Ramona', slug: 'ramona', gender: 'girl', origin: 'Spanish', meaning: 'Wise protector', popularity: 485 },
  { name: 'Raven', slug: 'raven-girl', gender: 'girl', origin: 'English', meaning: 'Blackbird', popularity: 345 },
  { name: 'Rayna', slug: 'rayna', gender: 'girl', origin: 'Hebrew', meaning: 'Song of the Lord', popularity: 285 },
  { name: 'Regina', slug: 'regina', gender: 'girl', origin: 'Latin', meaning: 'Queen', popularity: 398 },
  { name: 'Reina', slug: 'reina', gender: 'girl', origin: 'Spanish', meaning: 'Queen', popularity: 345 },
  { name: 'Remington', slug: 'remington-girl', gender: 'girl', origin: 'English', meaning: 'Raven town', popularity: 285 },
  { name: 'Renata', slug: 'renata', gender: 'girl', origin: 'Latin', meaning: 'Reborn', popularity: 485 },
  { name: 'Renee', slug: 'renee', gender: 'girl', origin: 'French', meaning: 'Reborn', popularity: 425 },
  { name: 'Rhea', slug: 'rhea', gender: 'girl', origin: 'Greek', meaning: 'Flowing', popularity: 398 },
  { name: 'Rita', slug: 'rita', gender: 'girl', origin: 'Sanskrit', meaning: 'Pearl', popularity: 512 },
  { name: 'Rivka', slug: 'rivka', gender: 'girl', origin: 'Hebrew', meaning: 'To bind', popularity: 512 },
  { name: 'Romina', slug: 'romina', gender: 'girl', origin: 'Latin', meaning: 'From Rome', popularity: 398 },
  { name: 'Rosalia', slug: 'rosalia', gender: 'girl', origin: 'Latin', meaning: 'Rose', popularity: 398 },
  { name: 'Rosalyn', slug: 'rosalyn', gender: 'girl', origin: 'Spanish', meaning: 'Pretty rose', popularity: 425 },
  { name: 'Rosanna', slug: 'rosanna', gender: 'girl', origin: 'Italian', meaning: 'Graceful rose', popularity: 512 },
  { name: 'Roselyn', slug: 'roselyn', gender: 'girl', origin: 'German', meaning: 'Gentle horse', popularity: 345 },
  { name: 'Rosie', slug: 'rosie', gender: 'girl', origin: 'English', meaning: 'Rose', popularity: 285 },
  { name: 'Royalty', slug: 'royalty', gender: 'girl', origin: 'English', meaning: 'Royal status', popularity: 398 },
  { name: 'Sabina', slug: 'sabina', gender: 'girl', origin: 'Latin', meaning: 'Sabine woman', popularity: 485 },
  { name: 'Saoirse', slug: 'saoirse', gender: 'girl', origin: 'Irish', meaning: 'Freedom', popularity: 398 },
  { name: 'Sasha', slug: 'sasha-girl', gender: 'girl', origin: 'Russian', meaning: 'Defender of mankind', popularity: 345 },
  { name: 'Sawyer', slug: 'sawyer-girl', gender: 'girl', origin: 'English', meaning: 'Woodcutter', popularity: 245 },
  { name: 'Selah', slug: 'selah', gender: 'girl', origin: 'Hebrew', meaning: 'Pause, reflect', popularity: 345 },
  { name: 'Serena', slug: 'serena', gender: 'girl', origin: 'Latin', meaning: 'Calm, tranquil', popularity: 285 },
  { name: 'Sevyn', slug: 'sevyn', gender: 'girl', origin: 'American', meaning: 'Seven', popularity: 512 },
  { name: 'Sharon', slug: 'sharon', gender: 'girl', origin: 'Hebrew', meaning: 'Plain of Sharon', popularity: 512 },
  { name: 'Shirley', slug: 'shirley', gender: 'girl', origin: 'English', meaning: 'Bright meadow', popularity: 512 },
  { name: 'Sierra', slug: 'sierra', gender: 'girl', origin: 'Spanish', meaning: 'Mountain range', popularity: 188 },
  { name: 'Simone', slug: 'simone', gender: 'girl', origin: 'Hebrew', meaning: 'Heard', popularity: 345 },
  { name: 'Skye', slug: 'skye', gender: 'girl', origin: 'Scottish', meaning: 'Cloud', popularity: 285 },
  { name: 'Sloan', slug: 'sloan', gender: 'girl', origin: 'Irish', meaning: 'Raider', popularity: 345 },
  { name: 'Soleil', slug: 'soleil', gender: 'girl', origin: 'French', meaning: 'Sun', popularity: 512 },
  { name: 'Sonia', slug: 'sonia', gender: 'girl', origin: 'Slavic', meaning: 'Wisdom', popularity: 485 },
  { name: 'Spencer', slug: 'spencer-girl', gender: 'girl', origin: 'English', meaning: 'Steward', popularity: 398 },
  { name: 'Starla', slug: 'starla', gender: 'girl', origin: 'English', meaning: 'Star', popularity: 512 },
  { name: 'Stevie', slug: 'stevie-girl', gender: 'girl', origin: 'Greek', meaning: 'Crown', popularity: 345 },
  { name: 'Susan', slug: 'susan', gender: 'girl', origin: 'Hebrew', meaning: 'Lily', popularity: 512 },
  { name: 'Sutton', slug: 'sutton-girl', gender: 'girl', origin: 'English', meaning: 'South town', popularity: 285 },
  { name: 'Sylvia', slug: 'sylvia', gender: 'girl', origin: 'Latin', meaning: 'Forest', popularity: 398 },
  { name: 'Sylvie', slug: 'sylvie', gender: 'girl', origin: 'French', meaning: 'Forest', popularity: 425 },
  { name: 'Tabitha', slug: 'tabitha', gender: 'girl', origin: 'Aramaic', meaning: 'Gazelle', popularity: 512 },
  { name: 'Tamara', slug: 'tamara', gender: 'girl', origin: 'Hebrew', meaning: 'Date palm', popularity: 485 },
  { name: 'Tiana', slug: 'tiana', gender: 'girl', origin: 'Latin', meaning: 'Princess', popularity: 285 },
  { name: 'Tiffany', slug: 'tiffany', gender: 'girl', origin: 'Greek', meaning: 'Appearance of God', popularity: 398 },
  { name: 'Tinsley', slug: 'tinsley', gender: 'girl', origin: 'English', meaning: 'Tynni\'s meadow', popularity: 398 },
  { name: 'Tori', slug: 'tori', gender: 'girl', origin: 'Latin', meaning: 'Winner', popularity: 425 },
  { name: 'Treasure', slug: 'treasure', gender: 'girl', origin: 'English', meaning: 'Valuable thing', popularity: 485 },
  { name: 'Trisha', slug: 'trisha', gender: 'girl', origin: 'Latin', meaning: 'Noble', popularity: 512 },
  { name: 'Uma', slug: 'uma', gender: 'girl', origin: 'Sanskrit', meaning: 'Tranquility', popularity: 485 },
  { name: 'Unique', slug: 'unique', gender: 'girl', origin: 'English', meaning: 'One of a kind', popularity: 485 },
  { name: 'Ursula', slug: 'ursula', gender: 'girl', origin: 'Latin', meaning: 'Little bear', popularity: 512 },
  { name: 'Valentina', slug: 'valentina', gender: 'girl', origin: 'Latin', meaning: 'Strength, health', popularity: 75 },
  { name: 'Veda', slug: 'veda', gender: 'girl', origin: 'Sanskrit', meaning: 'Knowledge', popularity: 485 },
  { name: 'Vera', slug: 'vera', gender: 'girl', origin: 'Slavic', meaning: 'Faith, truth', popularity: 258 },
  { name: 'Vida', slug: 'vida', gender: 'girl', origin: 'Spanish', meaning: 'Life', popularity: 512 },
  { name: 'Virginia', slug: 'virginia', gender: 'girl', origin: 'Latin', meaning: 'Pure, virginal', popularity: 485 },
  { name: 'Waverly', slug: 'waverly', gender: 'girl', origin: 'English', meaning: 'Meadow of quivering aspens', popularity: 345 },
  { name: 'Wendy', slug: 'wendy', gender: 'girl', origin: 'English', meaning: 'Friend', popularity: 485 },
  { name: 'Whitney', slug: 'whitney', gender: 'girl', origin: 'English', meaning: 'White island', popularity: 485 },
  { name: 'Willa', slug: 'willa', gender: 'girl', origin: 'German', meaning: 'Resolute protector', popularity: 245 },
  { name: 'Wren', slug: 'wren-girl', gender: 'girl', origin: 'English', meaning: 'Small bird', popularity: 285 },
  { name: 'Wynter', slug: 'wynter', gender: 'girl', origin: 'American', meaning: 'Winter season', popularity: 398 },
  { name: 'Xiomara', slug: 'xiomara', gender: 'girl', origin: 'Spanish', meaning: 'Ready for battle', popularity: 398 },
  { name: 'Ximena', slug: 'ximena', gender: 'girl', origin: 'Spanish', meaning: 'Listener', popularity: 178 },
  { name: 'Yareli', slug: 'yareli', gender: 'girl', origin: 'Native American', meaning: 'Water lady', popularity: 398 },
  { name: 'Yaretzi', slug: 'yaretzi', gender: 'girl', origin: 'Aztec', meaning: 'You will always be loved', popularity: 345 },
  { name: 'Yesenia', slug: 'yesenia', gender: 'girl', origin: 'Arabic', meaning: 'Flower', popularity: 425 },
  { name: 'Yolanda', slug: 'yolanda', gender: 'girl', origin: 'Greek', meaning: 'Violet flower', popularity: 512 },
  { name: 'Yvette', slug: 'yvette', gender: 'girl', origin: 'French', meaning: 'Yew tree', popularity: 512 },
  { name: 'Yvonne', slug: 'yvonne', gender: 'girl', origin: 'French', meaning: 'Yew tree', popularity: 512 },
  { name: 'Zahara', slug: 'zahara', gender: 'girl', origin: 'Arabic', meaning: 'Flowering', popularity: 398 },
  { name: 'Zaniyah', slug: 'zaniyah', gender: 'girl', origin: 'American', meaning: 'Forever, always', popularity: 398 },
  { name: 'Zelda', slug: 'zelda', gender: 'girl', origin: 'German', meaning: 'Gray fighting maid', popularity: 512 },
  { name: 'Zendaya', slug: 'zendaya', gender: 'girl', origin: 'Shona', meaning: 'To give thanks', popularity: 485 },
  { name: 'Zion', slug: 'zion-girl', gender: 'girl', origin: 'Hebrew', meaning: 'Highest point', popularity: 345 },
  { name: 'Zoie', slug: 'zoie', gender: 'girl', origin: 'Greek', meaning: 'Life', popularity: 398 },
  { name: 'Zola', slug: 'zola', gender: 'girl', origin: 'Italian', meaning: 'Earth', popularity: 512 },
  { name: 'Zora', slug: 'zora', gender: 'girl', origin: 'Slavic', meaning: 'Dawn', popularity: 485 },
];

const moreBoyNames = [
  { name: 'Ian', slug: 'ian', gender: 'boy', origin: 'Scottish', meaning: 'God is gracious', popularity: 85 },
  { name: 'Ibrahim', slug: 'ibrahim', gender: 'boy', origin: 'Arabic', meaning: 'Father of nations', popularity: 285 },
  { name: 'Ignacio', slug: 'ignacio', gender: 'boy', origin: 'Spanish', meaning: 'Fiery', popularity: 485 },
  { name: 'Iker', slug: 'iker', gender: 'boy', origin: 'Basque', meaning: 'Visitation', popularity: 285 },
  { name: 'Irving', slug: 'irving', gender: 'boy', origin: 'Scottish', meaning: 'Green water', popularity: 512 },
  { name: 'Isaac', slug: 'isaac', gender: 'boy', origin: 'Hebrew', meaning: 'He will laugh', popularity: 32 },
  { name: 'Isaiah', slug: 'isaiah', gender: 'boy', origin: 'Hebrew', meaning: 'Salvation of the Lord', popularity: 42 },
  { name: 'Ismael', slug: 'ismael', gender: 'boy', origin: 'Hebrew', meaning: 'God will hear', popularity: 385 },
  { name: 'Israel', slug: 'israel', gender: 'boy', origin: 'Hebrew', meaning: 'God contends', popularity: 225 },
  { name: 'Ivan', slug: 'ivan', gender: 'boy', origin: 'Russian', meaning: 'God is gracious', popularity: 178 },
  { name: 'Jace', slug: 'jace', gender: 'boy', origin: 'American', meaning: 'Healer', popularity: 72 },
  { name: 'Jack', slug: 'jack', gender: 'boy', origin: 'English', meaning: 'God is gracious', popularity: 18 },
  { name: 'Jackson', slug: 'jackson', gender: 'boy', origin: 'English', meaning: 'Son of Jack', popularity: 14 },
  { name: 'Jacob', slug: 'jacob', gender: 'boy', origin: 'Hebrew', meaning: 'Supplanter', popularity: 22 },
  { name: 'Jaden', slug: 'jaden-boy', gender: 'boy', origin: 'Hebrew', meaning: 'Thankful', popularity: 145 },
  { name: 'Jaiden', slug: 'jaiden', gender: 'boy', origin: 'Hebrew', meaning: 'Thankful', popularity: 185 },
  { name: 'Jake', slug: 'jake', gender: 'boy', origin: 'Hebrew', meaning: 'Supplanter', popularity: 285 },
  { name: 'Jalen', slug: 'jalen', gender: 'boy', origin: 'American', meaning: 'Thankful', popularity: 345 },
  { name: 'Jamal', slug: 'jamal', gender: 'boy', origin: 'Arabic', meaning: 'Handsome', popularity: 485 },
  { name: 'James', slug: 'james', gender: 'boy', origin: 'Hebrew', meaning: 'Supplanter', popularity: 5 },
  { name: 'Jameson', slug: 'jameson', gender: 'boy', origin: 'English', meaning: 'Son of James', popularity: 85 },
  { name: 'Jared', slug: 'jared', gender: 'boy', origin: 'Hebrew', meaning: 'Descending', popularity: 385 },
  { name: 'Jasper', slug: 'jasper', gender: 'boy', origin: 'Persian', meaning: 'Treasurer', popularity: 105 },
  { name: 'Javier', slug: 'javier', gender: 'boy', origin: 'Spanish', meaning: 'New house', popularity: 225 },
  { name: 'Jax', slug: 'jax', gender: 'boy', origin: 'English', meaning: 'Son of Jack', popularity: 62 },
  { name: 'Jaxon', slug: 'jaxon', gender: 'boy', origin: 'English', meaning: 'Son of Jack', popularity: 35 },
  { name: 'Jaxson', slug: 'jaxson', gender: 'boy', origin: 'English', meaning: 'Son of Jack', popularity: 85 },
  { name: 'Jayden', slug: 'jayden', gender: 'boy', origin: 'Hebrew', meaning: 'Thankful', popularity: 35 },
  { name: 'Jaylen', slug: 'jaylen', gender: 'boy', origin: 'American', meaning: 'Thankful', popularity: 285 },
  { name: 'Jayson', slug: 'jayson', gender: 'boy', origin: 'Greek', meaning: 'Healer', popularity: 385 },
  { name: 'Jeffrey', slug: 'jeffrey', gender: 'boy', origin: 'German', meaning: 'Peaceful pledge', popularity: 425 },
  { name: 'Jeremiah', slug: 'jeremiah', gender: 'boy', origin: 'Hebrew', meaning: 'Exalted by God', popularity: 52 },
  { name: 'Jeremy', slug: 'jeremy', gender: 'boy', origin: 'Hebrew', meaning: 'Exalted by God', popularity: 285 },
  { name: 'Jerry', slug: 'jerry', gender: 'boy', origin: 'German', meaning: 'Spear ruler', popularity: 512 },
  { name: 'Jesse', slug: 'jesse-boy', gender: 'boy', origin: 'Hebrew', meaning: 'Gift', popularity: 178 },
  { name: 'Jesus', slug: 'jesus', gender: 'boy', origin: 'Hebrew', meaning: 'God is salvation', popularity: 145 },
  { name: 'Jimmy', slug: 'jimmy', gender: 'boy', origin: 'Hebrew', meaning: 'Supplanter', popularity: 512 },
  { name: 'Joel', slug: 'joel', gender: 'boy', origin: 'Hebrew', meaning: 'Yahweh is God', popularity: 178 },
  { name: 'John', slug: 'john', gender: 'boy', origin: 'Hebrew', meaning: 'God is gracious', popularity: 32 },
  { name: 'Johnny', slug: 'johnny', gender: 'boy', origin: 'Hebrew', meaning: 'God is gracious', popularity: 385 },
  { name: 'Jonah', slug: 'jonah', gender: 'boy', origin: 'Hebrew', meaning: 'Dove', popularity: 125 },
  { name: 'Jonas', slug: 'jonas', gender: 'boy', origin: 'Hebrew', meaning: 'Dove', popularity: 178 },
  { name: 'Jonathan', slug: 'jonathan', gender: 'boy', origin: 'Hebrew', meaning: 'God has given', popularity: 78 },
  { name: 'Jorge', slug: 'jorge', gender: 'boy', origin: 'Spanish', meaning: 'Farmer', popularity: 285 },
  { name: 'Jose', slug: 'jose', gender: 'boy', origin: 'Spanish', meaning: 'God will increase', popularity: 85 },
  { name: 'Joseph', slug: 'joseph', gender: 'boy', origin: 'Hebrew', meaning: 'God will increase', popularity: 25 },
  { name: 'Joshua', slug: 'joshua', gender: 'boy', origin: 'Hebrew', meaning: 'God is salvation', popularity: 48 },
  { name: 'Josiah', slug: 'josiah', gender: 'boy', origin: 'Hebrew', meaning: 'God supports', popularity: 52 },
  { name: 'Josue', slug: 'josue', gender: 'boy', origin: 'Spanish', meaning: 'God is salvation', popularity: 285 },
  { name: 'Juan', slug: 'juan', gender: 'boy', origin: 'Spanish', meaning: 'God is gracious', popularity: 145 },
  { name: 'Judah', slug: 'judah', gender: 'boy', origin: 'Hebrew', meaning: 'Praised', popularity: 145 },
  { name: 'Jude', slug: 'jude', gender: 'boy', origin: 'Greek', meaning: 'Praised', popularity: 85 },
  { name: 'Julian', slug: 'julian', gender: 'boy', origin: 'Latin', meaning: 'Youthful', popularity: 32 },
  { name: 'Julio', slug: 'julio', gender: 'boy', origin: 'Spanish', meaning: 'Youthful', popularity: 385 },
  { name: 'Julius', slug: 'julius', gender: 'boy', origin: 'Latin', meaning: 'Youthful', popularity: 285 },
  { name: 'Justin', slug: 'justin', gender: 'boy', origin: 'Latin', meaning: 'Just, fair', popularity: 145 },
  { name: 'Kaden', slug: 'kaden', gender: 'boy', origin: 'American', meaning: 'Companion', popularity: 225 },
  { name: 'Kai', slug: 'kai-boy', gender: 'boy', origin: 'Hawaiian', meaning: 'Sea', popularity: 72 },
  { name: 'Kaleb', slug: 'kaleb', gender: 'boy', origin: 'Hebrew', meaning: 'Faithful', popularity: 225 },
  { name: 'Kane', slug: 'kane', gender: 'boy', origin: 'Celtic', meaning: 'Warrior', popularity: 285 },
  { name: 'Kayden', slug: 'kayden', gender: 'boy', origin: 'American', meaning: 'Fighter', popularity: 145 },
  { name: 'Kayson', slug: 'kayson', gender: 'boy', origin: 'American', meaning: 'Rejoice', popularity: 285 },
  { name: 'Keegan', slug: 'keegan', gender: 'boy', origin: 'Irish', meaning: 'Small flame', popularity: 285 },
  { name: 'Keith', slug: 'keith', gender: 'boy', origin: 'Scottish', meaning: 'Woods', popularity: 512 },
  { name: 'Kellan', slug: 'kellan', gender: 'boy', origin: 'Irish', meaning: 'Slender', popularity: 385 },
  { name: 'Kenneth', slug: 'kenneth', gender: 'boy', origin: 'Scottish', meaning: 'Born of fire', popularity: 285 },
  { name: 'Kevin', slug: 'kevin', gender: 'boy', origin: 'Irish', meaning: 'Handsome', popularity: 145 },
  { name: 'Khalid', slug: 'khalid', gender: 'boy', origin: 'Arabic', meaning: 'Eternal', popularity: 385 },
  { name: 'Khalil', slug: 'khalil', gender: 'boy', origin: 'Arabic', meaning: 'Friend', popularity: 285 },
  { name: 'Killian', slug: 'killian', gender: 'boy', origin: 'Irish', meaning: 'Church', popularity: 225 },
  { name: 'King', slug: 'king', gender: 'boy', origin: 'English', meaning: 'Monarch', popularity: 225 },
  { name: 'Kingston', slug: 'kingston', gender: 'boy', origin: 'English', meaning: 'King\'s town', popularity: 85 },
  { name: 'Knox', slug: 'knox', gender: 'boy', origin: 'Scottish', meaning: 'Round hill', popularity: 125 },
  { name: 'Kobe', slug: 'kobe', gender: 'boy', origin: 'Japanese', meaning: 'God\'s door', popularity: 385 },
  { name: 'Kolton', slug: 'kolton', gender: 'boy', origin: 'English', meaning: 'Coal town', popularity: 385 },
  { name: 'Kyle', slug: 'kyle', gender: 'boy', origin: 'Scottish', meaning: 'Narrow strait', popularity: 225 },
  { name: 'Kyler', slug: 'kyler', gender: 'boy', origin: 'Dutch', meaning: 'Archer', popularity: 285 },
  { name: 'Kyrie', slug: 'kyrie-boy', gender: 'boy', origin: 'Greek', meaning: 'Lord', popularity: 345 },
  { name: 'Landry', slug: 'landry-boy', gender: 'boy', origin: 'English', meaning: 'Ruler', popularity: 385 },
  { name: 'Landon', slug: 'landon', gender: 'boy', origin: 'English', meaning: 'Long hill', popularity: 55 },
  { name: 'Lane', slug: 'lane', gender: 'boy', origin: 'English', meaning: 'Roadway', popularity: 225 },
  { name: 'Larry', slug: 'larry', gender: 'boy', origin: 'Latin', meaning: 'Laurel', popularity: 512 },
  { name: 'Lawrence', slug: 'lawrence', gender: 'boy', origin: 'Latin', meaning: 'Laurel', popularity: 385 },
  { name: 'Lawson', slug: 'lawson', gender: 'boy', origin: 'English', meaning: 'Son of Lawrence', popularity: 345 },
  { name: 'Layton', slug: 'layton', gender: 'boy', origin: 'English', meaning: 'Settlement with a leek garden', popularity: 345 },
  { name: 'Leandro', slug: 'leandro', gender: 'boy', origin: 'Greek', meaning: 'Lion man', popularity: 398 },
  { name: 'Legend', slug: 'legend', gender: 'boy', origin: 'English', meaning: 'Story, myth', popularity: 178 },
  { name: 'Lennon', slug: 'lennon-boy', gender: 'boy', origin: 'Irish', meaning: 'Little cloak', popularity: 285 },
  { name: 'Lennox', slug: 'lennox-boy', gender: 'boy', origin: 'Scottish', meaning: 'Elm grove', popularity: 225 },
  { name: 'Leo', slug: 'leo', gender: 'boy', origin: 'Latin', meaning: 'Lion', popularity: 22 },
  { name: 'Leon', slug: 'leon', gender: 'boy', origin: 'Greek', meaning: 'Lion', popularity: 178 },
  { name: 'Leonard', slug: 'leonard', gender: 'boy', origin: 'German', meaning: 'Brave lion', popularity: 385 },
  { name: 'Leonardo', slug: 'leonardo', gender: 'boy', origin: 'Italian', meaning: 'Brave lion', popularity: 62 },
  { name: 'Leonel', slug: 'leonel', gender: 'boy', origin: 'Latin', meaning: 'Young lion', popularity: 285 },
  { name: 'Leonidas', slug: 'leonidas', gender: 'boy', origin: 'Greek', meaning: 'Son of the lion', popularity: 345 },
  { name: 'Levi', slug: 'levi', gender: 'boy', origin: 'Hebrew', meaning: 'Joined, attached', popularity: 18 },
  { name: 'Lewis', slug: 'lewis', gender: 'boy', origin: 'English', meaning: 'Renowned warrior', popularity: 285 },
  { name: 'Liam', slug: 'liam', gender: 'boy', origin: 'Irish', meaning: 'Strong-willed warrior', popularity: 1 },
  { name: 'Lincoln', slug: 'lincoln', gender: 'boy', origin: 'English', meaning: 'Lake colony', popularity: 35 },
  { name: 'Lionel', slug: 'lionel', gender: 'boy', origin: 'Latin', meaning: 'Young lion', popularity: 385 },
  { name: 'Logan', slug: 'logan', gender: 'boy', origin: 'Scottish', meaning: 'Little hollow', popularity: 28 },
  { name: 'Lorenzo', slug: 'lorenzo', gender: 'boy', origin: 'Italian', meaning: 'From Laurentum', popularity: 145 },
  { name: 'Louis', slug: 'louis', gender: 'boy', origin: 'German', meaning: 'Famous warrior', popularity: 178 },
  { name: 'Luca', slug: 'luca', gender: 'boy', origin: 'Italian', meaning: 'Bringer of light', popularity: 35 },
  { name: 'Lucas', slug: 'lucas', gender: 'boy', origin: 'Greek', meaning: 'Bringer of light', popularity: 8 },
  { name: 'Luciano', slug: 'luciano', gender: 'boy', origin: 'Italian', meaning: 'Light', popularity: 285 },
  { name: 'Luis', slug: 'luis', gender: 'boy', origin: 'Spanish', meaning: 'Famous warrior', popularity: 145 },
  { name: 'Lukas', slug: 'lukas', gender: 'boy', origin: 'Greek', meaning: 'Bringer of light', popularity: 178 },
  { name: 'Luke', slug: 'luke', gender: 'boy', origin: 'Greek', meaning: 'Bringer of light', popularity: 28 },
  { name: 'Malcolm', slug: 'malcolm', gender: 'boy', origin: 'Scottish', meaning: 'Disciple of Saint Columba', popularity: 345 },
  { name: 'Malik', slug: 'malik', gender: 'boy', origin: 'Arabic', meaning: 'King', popularity: 285 },
  { name: 'Manuel', slug: 'manuel', gender: 'boy', origin: 'Spanish', meaning: 'God is with us', popularity: 285 },
  { name: 'Marco', slug: 'marco', gender: 'boy', origin: 'Italian', meaning: 'Warlike', popularity: 285 },
  { name: 'Marcos', slug: 'marcos', gender: 'boy', origin: 'Spanish', meaning: 'Warlike', popularity: 345 },
  { name: 'Marcus', slug: 'marcus', gender: 'boy', origin: 'Latin', meaning: 'Warlike', popularity: 145 },
  { name: 'Mario', slug: 'mario', gender: 'boy', origin: 'Italian', meaning: 'Warlike', popularity: 285 },
  { name: 'Mark', slug: 'mark', gender: 'boy', origin: 'Latin', meaning: 'Warlike', popularity: 285 },
  { name: 'Marshall', slug: 'marshall', gender: 'boy', origin: 'French', meaning: 'Horse keeper', popularity: 345 },
  { name: 'Martin', slug: 'martin', gender: 'boy', origin: 'Latin', meaning: 'Warlike', popularity: 285 },
  { name: 'Marvin', slug: 'marvin', gender: 'boy', origin: 'Welsh', meaning: 'Sea friend', popularity: 485 },
  { name: 'Mason', slug: 'mason', gender: 'boy', origin: 'English', meaning: 'Stone worker', popularity: 12 },
  { name: 'Mateo', slug: 'mateo', gender: 'boy', origin: 'Spanish', meaning: 'Gift of God', popularity: 15 },
  { name: 'Mathew', slug: 'mathew', gender: 'boy', origin: 'Hebrew', meaning: 'Gift of God', popularity: 285 },
  { name: 'Mathias', slug: 'mathias', gender: 'boy', origin: 'Greek', meaning: 'Gift of God', popularity: 285 },
  { name: 'Matteo', slug: 'matteo', gender: 'boy', origin: 'Italian', meaning: 'Gift of God', popularity: 78 },
  { name: 'Matthew', slug: 'matthew', gender: 'boy', origin: 'Hebrew', meaning: 'Gift of God', popularity: 32 },
  { name: 'Matthias', slug: 'matthias', gender: 'boy', origin: 'Greek', meaning: 'Gift of God', popularity: 285 },
  { name: 'Mauricio', slug: 'mauricio', gender: 'boy', origin: 'Spanish', meaning: 'Dark-skinned', popularity: 485 },
  { name: 'Maverick', slug: 'maverick', gender: 'boy', origin: 'American', meaning: 'Independent', popularity: 45 },
  { name: 'Max', slug: 'max-boy', gender: 'boy', origin: 'Latin', meaning: 'Greatest', popularity: 145 },
  { name: 'Maxim', slug: 'maxim', gender: 'boy', origin: 'Latin', meaning: 'Greatest', popularity: 385 },
  { name: 'Maximilian', slug: 'maximilian', gender: 'boy', origin: 'Latin', meaning: 'Greatest', popularity: 345 },
  { name: 'Maximiliano', slug: 'maximiliano', gender: 'boy', origin: 'Spanish', meaning: 'Greatest', popularity: 285 },
  { name: 'Maxwell', slug: 'maxwell', gender: 'boy', origin: 'Scottish', meaning: 'Great stream', popularity: 105 },
  { name: 'Mekhi', slug: 'mekhi', gender: 'boy', origin: 'Hebrew', meaning: 'Who is like God', popularity: 345 },
  { name: 'Melvin', slug: 'melvin', gender: 'boy', origin: 'Irish', meaning: 'Chief', popularity: 512 },
  { name: 'Memphis', slug: 'memphis', gender: 'boy', origin: 'Greek', meaning: 'Established and beautiful', popularity: 285 },
  { name: 'Messiah', slug: 'messiah', gender: 'boy', origin: 'Hebrew', meaning: 'Anointed one', popularity: 285 },
  { name: 'Micah', slug: 'micah', gender: 'boy', origin: 'Hebrew', meaning: 'Who is like God', popularity: 105 },
  { name: 'Michael', slug: 'michael', gender: 'boy', origin: 'Hebrew', meaning: 'Who is like God', popularity: 15 },
  { name: 'Miguel', slug: 'miguel', gender: 'boy', origin: 'Spanish', meaning: 'Who is like God', popularity: 145 },
  { name: 'Milan', slug: 'milan-boy', gender: 'boy', origin: 'Slavic', meaning: 'Gracious', popularity: 285 },
  { name: 'Miles', slug: 'miles', gender: 'boy', origin: 'Latin', meaning: 'Soldier', popularity: 55 },
  { name: 'Milo', slug: 'milo', gender: 'boy', origin: 'German', meaning: 'Mild, peaceful', popularity: 72 },
  { name: 'Mitchell', slug: 'mitchell', gender: 'boy', origin: 'English', meaning: 'Who is like God', popularity: 345 },
  { name: 'Mohamed', slug: 'mohamed', gender: 'boy', origin: 'Arabic', meaning: 'Praiseworthy', popularity: 285 },
  { name: 'Mohammad', slug: 'mohammad', gender: 'boy', origin: 'Arabic', meaning: 'Praiseworthy', popularity: 425 },
  { name: 'Mohammed', slug: 'mohammed', gender: 'boy', origin: 'Arabic', meaning: 'Praiseworthy', popularity: 485 },
  { name: 'Moises', slug: 'moises', gender: 'boy', origin: 'Spanish', meaning: 'Drawn from the water', popularity: 385 },
  { name: 'Moses', slug: 'moses', gender: 'boy', origin: 'Hebrew', meaning: 'Drawn from the water', popularity: 285 },
  { name: 'Muhammad', slug: 'muhammad', gender: 'boy', origin: 'Arabic', meaning: 'Praiseworthy', popularity: 285 },
  { name: 'Nash', slug: 'nash', gender: 'boy', origin: 'English', meaning: 'By the ash tree', popularity: 225 },
  { name: 'Nathan', slug: 'nathan', gender: 'boy', origin: 'Hebrew', meaning: 'He gave', popularity: 55 },
  { name: 'Nathaniel', slug: 'nathaniel', gender: 'boy', origin: 'Hebrew', meaning: 'Gift of God', popularity: 85 },
  { name: 'Nelson', slug: 'nelson', gender: 'boy', origin: 'English', meaning: 'Son of Neil', popularity: 385 },
  { name: 'Nicholas', slug: 'nicholas', gender: 'boy', origin: 'Greek', meaning: 'Victory of the people', popularity: 78 },
  { name: 'Nico', slug: 'nico', gender: 'boy', origin: 'Italian', meaning: 'Victory of the people', popularity: 178 },
  { name: 'Nicolas', slug: 'nicolas', gender: 'boy', origin: 'Greek', meaning: 'Victory of the people', popularity: 225 },
  { name: 'Niko', slug: 'niko', gender: 'boy', origin: 'Finnish', meaning: 'Victory of the people', popularity: 385 },
  { name: 'Nikolai', slug: 'nikolai', gender: 'boy', origin: 'Russian', meaning: 'Victory of the people', popularity: 345 },
  { name: 'Nixon', slug: 'nixon', gender: 'boy', origin: 'English', meaning: 'Son of Nicholas', popularity: 385 },
  { name: 'Noah', slug: 'noah', gender: 'boy', origin: 'Hebrew', meaning: 'Rest, comfort', popularity: 2 },
  { name: 'Noel', slug: 'noel', gender: 'boy', origin: 'French', meaning: 'Christmas', popularity: 285 },
  { name: 'Nolan', slug: 'nolan', gender: 'boy', origin: 'Irish', meaning: 'Noble', popularity: 62 },
  { name: 'Norman', slug: 'norman', gender: 'boy', origin: 'English', meaning: 'Northman', popularity: 512 },
  { name: 'Oakley', slug: 'oakley-boy', gender: 'boy', origin: 'English', meaning: 'Oak meadow', popularity: 285 },
  { name: 'Oliver', slug: 'oliver', gender: 'boy', origin: 'Latin', meaning: 'Olive tree', popularity: 3 },
  { name: 'Omar', slug: 'omar', gender: 'boy', origin: 'Arabic', meaning: 'Life', popularity: 178 },
  { name: 'Omari', slug: 'omari', gender: 'boy', origin: 'Swahili', meaning: 'God the highest', popularity: 385 },
  { name: 'Onyx', slug: 'onyx-boy', gender: 'boy', origin: 'Greek', meaning: 'Black gemstone', popularity: 345 },
  { name: 'Orlando', slug: 'orlando', gender: 'boy', origin: 'Italian', meaning: 'Famous land', popularity: 345 },
  { name: 'Oscar', slug: 'oscar', gender: 'boy', origin: 'Irish', meaning: 'God spear', popularity: 145 },
  { name: 'Osiris', slug: 'osiris', gender: 'boy', origin: 'Egyptian', meaning: 'Powerful, mighty', popularity: 485 },
  { name: 'Otis', slug: 'otis', gender: 'boy', origin: 'German', meaning: 'Wealthy', popularity: 285 },
  { name: 'Otto', slug: 'otto', gender: 'boy', origin: 'German', meaning: 'Wealthy', popularity: 345 },
  { name: 'Owen', slug: 'owen', gender: 'boy', origin: 'Welsh', meaning: 'Young warrior', popularity: 22 },
  { name: 'Pablo', slug: 'pablo', gender: 'boy', origin: 'Spanish', meaning: 'Small', popularity: 285 },
  { name: 'Parker', slug: 'parker-boy', gender: 'boy', origin: 'English', meaning: 'Park keeper', popularity: 95 },
  { name: 'Patrick', slug: 'patrick', gender: 'boy', origin: 'Latin', meaning: 'Noble', popularity: 178 },
  { name: 'Paul', slug: 'paul', gender: 'boy', origin: 'Latin', meaning: 'Small', popularity: 225 },
  { name: 'Paxton', slug: 'paxton', gender: 'boy', origin: 'English', meaning: 'Peace town', popularity: 178 },
  { name: 'Pedro', slug: 'pedro', gender: 'boy', origin: 'Spanish', meaning: 'Rock', popularity: 285 },
  { name: 'Peter', slug: 'peter', gender: 'boy', origin: 'Greek', meaning: 'Rock', popularity: 225 },
  { name: 'Philip', slug: 'philip', gender: 'boy', origin: 'Greek', meaning: 'Horse lover', popularity: 385 },
  { name: 'Phillip', slug: 'phillip', gender: 'boy', origin: 'Greek', meaning: 'Horse lover', popularity: 385 },
  { name: 'Phoenix', slug: 'phoenix', gender: 'boy', origin: 'Greek', meaning: 'Mythical bird', popularity: 125 },
  { name: 'Pierce', slug: 'pierce', gender: 'boy', origin: 'English', meaning: 'Rock', popularity: 385 },
  { name: 'Porter', slug: 'porter', gender: 'boy', origin: 'French', meaning: 'Gatekeeper', popularity: 285 },
  { name: 'Preston', slug: 'preston', gender: 'boy', origin: 'English', meaning: 'Priest\'s town', popularity: 225 },
  { name: 'Prince', slug: 'prince', gender: 'boy', origin: 'Latin', meaning: 'Royal son', popularity: 285 },
  { name: 'Princeton', slug: 'princeton', gender: 'boy', origin: 'English', meaning: 'Princely town', popularity: 385 },
  { name: 'Quentin', slug: 'quentin', gender: 'boy', origin: 'Latin', meaning: 'Fifth', popularity: 345 },
  { name: 'Quincy', slug: 'quincy', gender: 'boy', origin: 'French', meaning: 'Fifth', popularity: 385 },
  { name: 'Quinn', slug: 'quinn-boy', gender: 'boy', origin: 'Irish', meaning: 'Wise', popularity: 285 },
  { name: 'Rafael', slug: 'rafael', gender: 'boy', origin: 'Spanish', meaning: 'God has healed', popularity: 178 },
  { name: 'Raiden', slug: 'raiden', gender: 'boy', origin: 'Japanese', meaning: 'Thunder and lightning', popularity: 225 },
  { name: 'Ralph', slug: 'ralph', gender: 'boy', origin: 'English', meaning: 'Wolf counsel', popularity: 512 },
  { name: 'Ramon', slug: 'ramon', gender: 'boy', origin: 'Spanish', meaning: 'Wise protector', popularity: 385 },
  { name: 'Ramsey', slug: 'ramsey', gender: 'boy', origin: 'English', meaning: 'Wild garlic island', popularity: 385 },
  { name: 'Randall', slug: 'randall', gender: 'boy', origin: 'English', meaning: 'Shield wolf', popularity: 512 },
  { name: 'Randy', slug: 'randy', gender: 'boy', origin: 'English', meaning: 'Shield wolf', popularity: 512 },
  { name: 'Raphael', slug: 'raphael', gender: 'boy', origin: 'Hebrew', meaning: 'God has healed', popularity: 285 },
  { name: 'Raul', slug: 'raul', gender: 'boy', origin: 'Spanish', meaning: 'Wolf counsel', popularity: 385 },
  { name: 'Ray', slug: 'ray', gender: 'boy', origin: 'English', meaning: 'Wise protector', popularity: 385 },
  { name: 'Raymond', slug: 'raymond', gender: 'boy', origin: 'German', meaning: 'Wise protector', popularity: 345 },
  { name: 'Raylan', slug: 'raylan', gender: 'boy', origin: 'American', meaning: 'Beam of light', popularity: 285 },
  { name: 'Reed', slug: 'reed', gender: 'boy', origin: 'English', meaning: 'Red-haired', popularity: 345 },
  { name: 'Reid', slug: 'reid', gender: 'boy', origin: 'English', meaning: 'Red-haired', popularity: 225 },
  { name: 'Remington', slug: 'remington', gender: 'boy', origin: 'English', meaning: 'Raven town', popularity: 225 },
  { name: 'Remy', slug: 'remy', gender: 'boy', origin: 'French', meaning: 'Oarsman', popularity: 285 },
  { name: 'Rhett', slug: 'rhett', gender: 'boy', origin: 'Welsh', meaning: 'Ardent', popularity: 145 },
  { name: 'Ricardo', slug: 'ricardo', gender: 'boy', origin: 'Spanish', meaning: 'Powerful ruler', popularity: 285 },
  { name: 'Richard', slug: 'richard', gender: 'boy', origin: 'German', meaning: 'Powerful ruler', popularity: 178 },
  { name: 'Ricky', slug: 'ricky', gender: 'boy', origin: 'German', meaning: 'Powerful ruler', popularity: 425 },
  { name: 'River', slug: 'river-boy', gender: 'boy', origin: 'English', meaning: 'Flowing water', popularity: 145 },
  { name: 'Robert', slug: 'robert', gender: 'boy', origin: 'German', meaning: 'Bright fame', popularity: 78 },
  { name: 'Roberto', slug: 'roberto', gender: 'boy', origin: 'Spanish', meaning: 'Bright fame', popularity: 285 },
  { name: 'Rocco', slug: 'rocco', gender: 'boy', origin: 'Italian', meaning: 'Rest', popularity: 285 },
  { name: 'Rocky', slug: 'rocky', gender: 'boy', origin: 'Italian', meaning: 'Rest', popularity: 385 },
  { name: 'Rodney', slug: 'rodney', gender: 'boy', origin: 'English', meaning: 'Famous island', popularity: 512 },
  { name: 'Rodrigo', slug: 'rodrigo', gender: 'boy', origin: 'Spanish', meaning: 'Famous power', popularity: 285 },
  { name: 'Roger', slug: 'roger', gender: 'boy', origin: 'German', meaning: 'Famous spear', popularity: 512 },
  { name: 'Rohan', slug: 'rohan', gender: 'boy', origin: 'Irish', meaning: 'Red-haired', popularity: 285 },
  { name: 'Roland', slug: 'roland', gender: 'boy', origin: 'German', meaning: 'Famous land', popularity: 512 },
  { name: 'Roman', slug: 'roman', gender: 'boy', origin: 'Latin', meaning: 'Citizen of Rome', popularity: 72 },
  { name: 'Romeo', slug: 'romeo', gender: 'boy', origin: 'Italian', meaning: 'Pilgrim to Rome', popularity: 285 },
  { name: 'Ronald', slug: 'ronald', gender: 'boy', origin: 'Norse', meaning: 'Advice ruler', popularity: 512 },
  { name: 'Ronan', slug: 'ronan', gender: 'boy', origin: 'Irish', meaning: 'Little seal', popularity: 178 },
  { name: 'Ronin', slug: 'ronin', gender: 'boy', origin: 'Japanese', meaning: 'Samurai without a master', popularity: 225 },
  { name: 'Ronnie', slug: 'ronnie', gender: 'boy', origin: 'Norse', meaning: 'Advice ruler', popularity: 485 },
  { name: 'Rowan', slug: 'rowan-boy', gender: 'boy', origin: 'Irish', meaning: 'Little red-haired one', popularity: 145 },
  { name: 'Roy', slug: 'roy', gender: 'boy', origin: 'French', meaning: 'King', popularity: 485 },
  { name: 'Royce', slug: 'royce', gender: 'boy', origin: 'English', meaning: 'Royal', popularity: 345 },
  { name: 'Ruben', slug: 'ruben', gender: 'boy', origin: 'Hebrew', meaning: 'Behold a son', popularity: 285 },
  { name: 'Russell', slug: 'russell', gender: 'boy', origin: 'French', meaning: 'Red-haired', popularity: 485 },
  { name: 'Ryan', slug: 'ryan', gender: 'boy', origin: 'Irish', meaning: 'Little king', popularity: 52 },
  { name: 'Ryder', slug: 'ryder', gender: 'boy', origin: 'English', meaning: 'Knight', popularity: 85 },
  { name: 'Ryker', slug: 'ryker', gender: 'boy', origin: 'German', meaning: 'Rich', popularity: 145 },
  { name: 'Rylan', slug: 'rylan', gender: 'boy', origin: 'Irish', meaning: 'Island meadow', popularity: 178 },
  { name: 'Sage', slug: 'sage-boy', gender: 'boy', origin: 'Latin', meaning: 'Wise', popularity: 285 },
  { name: 'Saint', slug: 'saint', gender: 'boy', origin: 'English', meaning: 'Holy person', popularity: 385 },
  { name: 'Salvador', slug: 'salvador', gender: 'boy', origin: 'Spanish', meaning: 'Savior', popularity: 385 },
  { name: 'Salvatore', slug: 'salvatore', gender: 'boy', origin: 'Italian', meaning: 'Savior', popularity: 512 },
  { name: 'Sam', slug: 'sam-boy', gender: 'boy', origin: 'Hebrew', meaning: 'Heard by God', popularity: 285 },
  { name: 'Samson', slug: 'samson', gender: 'boy', origin: 'Hebrew', meaning: 'Sun', popularity: 345 },
  { name: 'Samuel', slug: 'samuel', gender: 'boy', origin: 'Hebrew', meaning: 'Heard by God', popularity: 22 },
  { name: 'Santiago', slug: 'santiago', gender: 'boy', origin: 'Spanish', meaning: 'Saint James', popularity: 72 },
  { name: 'Santos', slug: 'santos', gender: 'boy', origin: 'Spanish', meaning: 'Saints', popularity: 512 },
  { name: 'Saul', slug: 'saul', gender: 'boy', origin: 'Hebrew', meaning: 'Asked for', popularity: 385 },
  { name: 'Sawyer', slug: 'sawyer', gender: 'boy', origin: 'English', meaning: 'Woodcutter', popularity: 105 },
  { name: 'Scott', slug: 'scott', gender: 'boy', origin: 'Scottish', meaning: 'Scotsman', popularity: 385 },
  { name: 'Sean', slug: 'sean', gender: 'boy', origin: 'Irish', meaning: 'God is gracious', popularity: 225 },
  { name: 'Sebastian', slug: 'sebastian', gender: 'boy', origin: 'Greek', meaning: 'Venerable', popularity: 18 },
  { name: 'Sergio', slug: 'sergio', gender: 'boy', origin: 'Latin', meaning: 'Servant', popularity: 345 },
  { name: 'Seth', slug: 'seth', gender: 'boy', origin: 'Hebrew', meaning: 'Appointed', popularity: 285 },
  { name: 'Shane', slug: 'shane', gender: 'boy', origin: 'Irish', meaning: 'God is gracious', popularity: 312 },
  { name: 'Shawn', slug: 'shawn-boy', gender: 'boy', origin: 'Irish', meaning: 'God is gracious', popularity: 385 },
  { name: 'Silas', slug: 'silas', gender: 'boy', origin: 'Latin', meaning: 'Forest, woods', popularity: 85 },
  { name: 'Simon', slug: 'simon', gender: 'boy', origin: 'Hebrew', meaning: 'He has heard', popularity: 225 },
  { name: 'Skyler', slug: 'skyler-boy', gender: 'boy', origin: 'Dutch', meaning: 'Scholar', popularity: 285 },
  { name: 'Solomon', slug: 'solomon', gender: 'boy', origin: 'Hebrew', meaning: 'Peace', popularity: 285 },
  { name: 'Spencer', slug: 'spencer-boy', gender: 'boy', origin: 'English', meaning: 'Steward', popularity: 285 },
  { name: 'Stanley', slug: 'stanley', gender: 'boy', origin: 'English', meaning: 'Stone clearing', popularity: 512 },
  { name: 'Stefan', slug: 'stefan', gender: 'boy', origin: 'German', meaning: 'Crown', popularity: 385 },
  { name: 'Stephen', slug: 'stephen', gender: 'boy', origin: 'Greek', meaning: 'Crown', popularity: 285 },
  { name: 'Sterling', slug: 'sterling-boy', gender: 'boy', origin: 'English', meaning: 'Little star', popularity: 385 },
  { name: 'Steven', slug: 'steven', gender: 'boy', origin: 'Greek', meaning: 'Crown', popularity: 178 },
  { name: 'Sullivan', slug: 'sullivan', gender: 'boy', origin: 'Irish', meaning: 'Dark eyes', popularity: 285 },
  { name: 'Stetson', slug: 'stetson', gender: 'boy', origin: 'English', meaning: 'Son of Stet', popularity: 385 },
];

// Read the current data file
const dataFilePath = path.join(__dirname, '..', 'lib', 'data.ts');
let content = fs.readFileSync(dataFilePath, 'utf8');

// Find the position of "// Additional names - expansion to 2000+"
const insertPoint = content.indexOf('// Additional names - expansion to 2000+');
if (insertPoint === -1) {
  console.error('Could not find insertion point');
  process.exit(1);
}

// Prepare the new names to insert
const allNewNames = [...moreGirlNames, ...moreBoyNames];
const newNamesStr = allNewNames.map(n => {
  const meaningEscaped = n.meaning.replace(/'/g, "\\'");
  return `  { name: '${n.name}', slug: '${n.slug}', gender: '${n.gender}', origin: '${n.origin}', meaning: '${meaningEscaped}', popularity: ${n.popularity} },`;
}).join('\n');

// Insert before the comment
const newContent = content.slice(0, insertPoint) + '// Second expansion batch\n' + newNamesStr + '\n\n  ' + content.slice(insertPoint);

// Write the updated content
fs.writeFileSync(dataFilePath, newContent, 'utf8');

console.log(`Added ${allNewNames.length} more names to the database`);
console.log(`- Girl names: ${moreGirlNames.length}`);
console.log(`- Boy names: ${moreBoyNames.length}`);
