// Script to expand the baby names database to 2000+ names
const fs = require('fs');
const path = require('path');

// Additional girl names to add
const additionalGirlNames = [
  // A names
  { name: 'Aarya', slug: 'aarya', gender: 'girl', origin: 'Sanskrit', meaning: 'Noble, goddess', popularity: 412 },
  { name: 'Abby', slug: 'abby', gender: 'girl', origin: 'Hebrew', meaning: 'Father\'s joy', popularity: 358 },
  { name: 'Adelaide', slug: 'adelaide', gender: 'girl', origin: 'German', meaning: 'Noble natured', popularity: 125 },
  { name: 'Adrianna', slug: 'adrianna', gender: 'girl', origin: 'Latin', meaning: 'From Hadria', popularity: 298 },
  { name: 'Aisha', slug: 'aisha', gender: 'girl', origin: 'Arabic', meaning: 'Alive, living', popularity: 312 },
  { name: 'Aitana', slug: 'aitana', gender: 'girl', origin: 'Spanish', meaning: 'Glory', popularity: 425 },
  { name: 'Alanna', slug: 'alanna', gender: 'girl', origin: 'Irish', meaning: 'Harmony, peace', popularity: 428 },
  { name: 'Alayna', slug: 'alayna', gender: 'girl', origin: 'Irish', meaning: 'Beautiful, bright', popularity: 265 },
  { name: 'Aleah', slug: 'aleah', gender: 'girl', origin: 'Arabic', meaning: 'High, exalted', popularity: 485 },
  { name: 'Alena', slug: 'alena', gender: 'girl', origin: 'Greek', meaning: 'Light', popularity: 398 },
  { name: 'Alessandra', slug: 'alessandra', gender: 'girl', origin: 'Italian', meaning: 'Defender of mankind', popularity: 325 },
  { name: 'Alianna', slug: 'alianna', gender: 'girl', origin: 'Hebrew', meaning: 'My God has answered', popularity: 445 },
  { name: 'Alicia', slug: 'alicia', gender: 'girl', origin: 'German', meaning: 'Noble', popularity: 285 },
  { name: 'Aliyah', slug: 'aliyah', gender: 'girl', origin: 'Hebrew', meaning: 'Ascending', popularity: 215 },
  { name: 'Alma', slug: 'alma', gender: 'girl', origin: 'Latin', meaning: 'Nurturing, soul', popularity: 358 },
  { name: 'Alyson', slug: 'alyson', gender: 'girl', origin: 'German', meaning: 'Noble', popularity: 475 },
  { name: 'Amanda', slug: 'amanda', gender: 'girl', origin: 'Latin', meaning: 'Worthy of love', popularity: 312 },
  { name: 'Amber', slug: 'amber', gender: 'girl', origin: 'Arabic', meaning: 'Fossilized tree resin', popularity: 285 },
  { name: 'Amelina', slug: 'amelina', gender: 'girl', origin: 'German', meaning: 'Hardworking', popularity: 512 },
  { name: 'Amira', slug: 'amira', gender: 'girl', origin: 'Arabic', meaning: 'Princess', popularity: 178 },
  { name: 'Amy', slug: 'amy', gender: 'girl', origin: 'French', meaning: 'Beloved', popularity: 298 },
  { name: 'Anahi', slug: 'anahi', gender: 'girl', origin: 'Persian', meaning: 'Immortal', popularity: 365 },
  { name: 'Anaya', slug: 'anaya', gender: 'girl', origin: 'Sanskrit', meaning: 'Without a superior', popularity: 128 },
  { name: 'Angelica', slug: 'angelica', gender: 'girl', origin: 'Latin', meaning: 'Angelic', popularity: 325 },
  { name: 'Anika', slug: 'anika', gender: 'girl', origin: 'Sanskrit', meaning: 'Grace', popularity: 345 },
  { name: 'Aniya', slug: 'aniya', gender: 'girl', origin: 'Hebrew', meaning: 'God has answered', popularity: 285 },
  { name: 'Annalee', slug: 'annalee', gender: 'girl', origin: 'English', meaning: 'Grace meadow', popularity: 425 },
  { name: 'Annalise', slug: 'annalise', gender: 'girl', origin: 'German', meaning: 'Grace, devoted to God', popularity: 315 },
  { name: 'Annie', slug: 'annie', gender: 'girl', origin: 'English', meaning: 'Grace', popularity: 245 },
  { name: 'April', slug: 'april', gender: 'girl', origin: 'Latin', meaning: 'To open, spring', popularity: 385 },
  { name: 'Ariadne', slug: 'ariadne', gender: 'girl', origin: 'Greek', meaning: 'Most holy', popularity: 525 },
  { name: 'Arielle', slug: 'arielle', gender: 'girl', origin: 'Hebrew', meaning: 'Lion of God', popularity: 265 },
  { name: 'Armani', slug: 'armani', gender: 'girl', origin: 'Italian', meaning: 'Warrior', popularity: 378 },
  { name: 'Arya', slug: 'arya-girl', gender: 'girl', origin: 'Sanskrit', meaning: 'Noble', popularity: 95 },
  { name: 'Ashlyn', slug: 'ashlyn', gender: 'girl', origin: 'Irish', meaning: 'Dream', popularity: 275 },
  { name: 'Astrid', slug: 'astrid', gender: 'girl', origin: 'Norse', meaning: 'Divine strength', popularity: 312 },
  { name: 'Aubree', slug: 'aubree', gender: 'girl', origin: 'German', meaning: 'Elf ruler', popularity: 78 },
  { name: 'Aubrielle', slug: 'aubrielle', gender: 'girl', origin: 'French', meaning: 'Elf ruler', popularity: 345 },
  { name: 'Aurelia', slug: 'aurelia', gender: 'girl', origin: 'Latin', meaning: 'Golden', popularity: 285 },
  { name: 'Ava', slug: 'ava', gender: 'girl', origin: 'Latin', meaning: 'Life, bird', popularity: 5 },
  { name: 'Avalynn', slug: 'avalynn', gender: 'girl', origin: 'American', meaning: 'Beautiful breath of life', popularity: 158 },
  { name: 'Aviana', slug: 'aviana', gender: 'girl', origin: 'Latin', meaning: 'Bird-like', popularity: 285 },
  { name: 'Avianna', slug: 'avianna', gender: 'girl', origin: 'Latin', meaning: 'Bird-like', popularity: 325 },
  { name: 'Ayla', slug: 'ayla', gender: 'girl', origin: 'Hebrew', meaning: 'Oak tree', popularity: 112 },
  { name: 'Azalea', slug: 'azalea', gender: 'girl', origin: 'Greek', meaning: 'Dry flower', popularity: 285 },
  // B names
  { name: 'Barbara', slug: 'barbara', gender: 'girl', origin: 'Greek', meaning: 'Foreign, strange', popularity: 445 },
  { name: 'Baylee', slug: 'baylee', gender: 'girl', origin: 'English', meaning: 'Berry clearing', popularity: 385 },
  { name: 'Belen', slug: 'belen', gender: 'girl', origin: 'Spanish', meaning: 'Bethlehem', popularity: 435 },
  { name: 'Bellamy', slug: 'bellamy', gender: 'girl', origin: 'French', meaning: 'Beautiful friend', popularity: 428 },
  { name: 'Belle', slug: 'belle', gender: 'girl', origin: 'French', meaning: 'Beautiful', popularity: 345 },
  { name: 'Bexley', slug: 'bexley', gender: 'girl', origin: 'English', meaning: 'Box tree meadow', popularity: 398 },
  { name: 'Blaire', slug: 'blaire', gender: 'girl', origin: 'Scottish', meaning: 'Plain, field', popularity: 412 },
  { name: 'Blakely', slug: 'blakely', gender: 'girl', origin: 'English', meaning: 'Dark meadow', popularity: 225 },
  { name: 'Braelyn', slug: 'braelyn', gender: 'girl', origin: 'American', meaning: 'Combination name', popularity: 315 },
  { name: 'Bria', slug: 'bria', gender: 'girl', origin: 'Irish', meaning: 'Noble, strong', popularity: 412 },
  { name: 'Briar', slug: 'briar', gender: 'girl', origin: 'English', meaning: 'Thorny bush', popularity: 285 },
  { name: 'Bridgette', slug: 'bridgette', gender: 'girl', origin: 'Irish', meaning: 'Exalted one', popularity: 485 },
  { name: 'Brinley', slug: 'brinley', gender: 'girl', origin: 'English', meaning: 'Burnt meadow', popularity: 225 },
  { name: 'Bristol', slug: 'bristol', gender: 'girl', origin: 'English', meaning: 'Meeting place by the bridge', popularity: 298 },
  { name: 'Brittney', slug: 'brittney', gender: 'girl', origin: 'English', meaning: 'From Britain', popularity: 445 },
  { name: 'Brynlee', slug: 'brynlee', gender: 'girl', origin: 'Welsh', meaning: 'Hill meadow', popularity: 135 },
  { name: 'Brynn', slug: 'brynn', gender: 'girl', origin: 'Welsh', meaning: 'Hill', popularity: 175 },
  // C names
  { name: 'Cadence', slug: 'cadence', gender: 'girl', origin: 'Latin', meaning: 'Rhythm', popularity: 145 },
  { name: 'Cali', slug: 'cali', gender: 'girl', origin: 'Greek', meaning: 'Most beautiful', popularity: 245 },
  { name: 'Callie', slug: 'callie', gender: 'girl', origin: 'Greek', meaning: 'Beautiful', popularity: 175 },
  { name: 'Cameron', slug: 'cameron-girl', gender: 'girl', origin: 'Scottish', meaning: 'Crooked nose', popularity: 412 },
  { name: 'Camryn', slug: 'camryn', gender: 'girl', origin: 'Scottish', meaning: 'Crooked nose', popularity: 285 },
  { name: 'Cara', slug: 'cara', gender: 'girl', origin: 'Italian', meaning: 'Beloved', popularity: 425 },
  { name: 'Carly', slug: 'carly', gender: 'girl', origin: 'German', meaning: 'Free woman', popularity: 358 },
  { name: 'Carmen', slug: 'carmen', gender: 'girl', origin: 'Spanish', meaning: 'Garden', popularity: 285 },
  { name: 'Carolina', slug: 'carolina', gender: 'girl', origin: 'German', meaning: 'Free woman', popularity: 315 },
  { name: 'Cassandra', slug: 'cassandra', gender: 'girl', origin: 'Greek', meaning: 'Shining upon men', popularity: 385 },
  { name: 'Cassidy', slug: 'cassidy', gender: 'girl', origin: 'Irish', meaning: 'Clever', popularity: 312 },
  { name: 'Cataleya', slug: 'cataleya', gender: 'girl', origin: 'Spanish', meaning: 'Orchid flower', popularity: 195 },
  { name: 'Caylee', slug: 'caylee', gender: 'girl', origin: 'Irish', meaning: 'Slender', popularity: 425 },
  { name: 'Cecelia', slug: 'cecelia', gender: 'girl', origin: 'Latin', meaning: 'Blind', popularity: 285 },
  { name: 'Charlee', slug: 'charlee', gender: 'girl', origin: 'German', meaning: 'Free woman', popularity: 178 },
  { name: 'Charleigh', slug: 'charleigh', gender: 'girl', origin: 'German', meaning: 'Free woman', popularity: 285 },
  { name: 'Charlie', slug: 'charlie-girl', gender: 'girl', origin: 'German', meaning: 'Free woman', popularity: 145 },
  { name: 'Chaya', slug: 'chaya', gender: 'girl', origin: 'Hebrew', meaning: 'Life', popularity: 445 },
  { name: 'Chelsey', slug: 'chelsey', gender: 'girl', origin: 'English', meaning: 'Chalk landing place', popularity: 485 },
  { name: 'Cheyenne', slug: 'cheyenne', gender: 'girl', origin: 'Native American', meaning: 'Unintelligible speakers', popularity: 312 },
  { name: 'Christina', slug: 'christina', gender: 'girl', origin: 'Greek', meaning: 'Follower of Christ', popularity: 425 },
  { name: 'Clarissa', slug: 'clarissa', gender: 'girl', origin: 'Latin', meaning: 'Bright, clear', popularity: 445 },
  { name: 'Colette', slug: 'colette', gender: 'girl', origin: 'French', meaning: 'Victory of the people', popularity: 385 },
  { name: 'Collins', slug: 'collins', gender: 'girl', origin: 'Irish', meaning: 'Holly', popularity: 315 },
  { name: 'Coraline', slug: 'coraline', gender: 'girl', origin: 'English', meaning: 'Coral', popularity: 425 },
  { name: 'Crystal', slug: 'crystal', gender: 'girl', origin: 'Greek', meaning: 'Ice, crystal', popularity: 385 },
  // D names
  { name: 'Daleyza', slug: 'daleyza', gender: 'girl', origin: 'Spanish', meaning: 'Delightful', popularity: 245 },
  { name: 'Dallas', slug: 'dallas-girl', gender: 'girl', origin: 'Scottish', meaning: 'Meadow dwelling', popularity: 345 },
  { name: 'Dana', slug: 'dana', gender: 'girl', origin: 'Hebrew', meaning: 'God is my judge', popularity: 425 },
  { name: 'Danica', slug: 'danica', gender: 'girl', origin: 'Slavic', meaning: 'Morning star', popularity: 485 },
  { name: 'Daniella', slug: 'daniella', gender: 'girl', origin: 'Hebrew', meaning: 'God is my judge', popularity: 225 },
  { name: 'Danielle', slug: 'danielle', gender: 'girl', origin: 'Hebrew', meaning: 'God is my judge', popularity: 285 },
  { name: 'Danna', slug: 'danna', gender: 'girl', origin: 'Hebrew', meaning: 'God is my judge', popularity: 345 },
  { name: 'Davina', slug: 'davina', gender: 'girl', origin: 'Hebrew', meaning: 'Beloved', popularity: 512 },
  { name: 'Dayana', slug: 'dayana', gender: 'girl', origin: 'Latin', meaning: 'Divine', popularity: 385 },
  { name: 'Deborah', slug: 'deborah', gender: 'girl', origin: 'Hebrew', meaning: 'Bee', popularity: 445 },
  { name: 'Della', slug: 'della', gender: 'girl', origin: 'German', meaning: 'Noble', popularity: 385 },
  { name: 'Denise', slug: 'denise', gender: 'girl', origin: 'French', meaning: 'Devoted to Dionysus', popularity: 485 },
  { name: 'Denver', slug: 'denver-girl', gender: 'girl', origin: 'English', meaning: 'Green valley', popularity: 365 },
  { name: 'Dorothy', slug: 'dorothy', gender: 'girl', origin: 'Greek', meaning: 'Gift of God', popularity: 385 },
  { name: 'Dream', slug: 'dream', gender: 'girl', origin: 'English', meaning: 'Vision, fantasy', popularity: 398 },
  { name: 'Drew', slug: 'drew-girl', gender: 'girl', origin: 'Greek', meaning: 'Wise', popularity: 485 },
  { name: 'Dulce', slug: 'dulce', gender: 'girl', origin: 'Spanish', meaning: 'Sweet', popularity: 385 },
  // E names
  { name: 'Edith', slug: 'edith', gender: 'girl', origin: 'English', meaning: 'Prosperous in war', popularity: 385 },
  { name: 'Eileen', slug: 'eileen', gender: 'girl', origin: 'Irish', meaning: 'Light', popularity: 465 },
  { name: 'Elaina', slug: 'elaina', gender: 'girl', origin: 'Greek', meaning: 'Shining light', popularity: 165 },
  { name: 'Elaine', slug: 'elaine', gender: 'girl', origin: 'French', meaning: 'Shining light', popularity: 425 },
  { name: 'Elani', slug: 'elani', gender: 'girl', origin: 'Hawaiian', meaning: 'Tree', popularity: 485 },
  { name: 'Elayna', slug: 'elayna', gender: 'girl', origin: 'Greek', meaning: 'Light', popularity: 385 },
  { name: 'Elektra', slug: 'elektra', gender: 'girl', origin: 'Greek', meaning: 'Shining, bright', popularity: 525 },
  { name: 'Elena', slug: 'elena', gender: 'girl', origin: 'Greek', meaning: 'Bright, shining light', popularity: 53 },
  { name: 'Elianna', slug: 'elianna', gender: 'girl', origin: 'Hebrew', meaning: 'My God has answered', popularity: 145 },
  { name: 'Elisabeth', slug: 'elisabeth', gender: 'girl', origin: 'Hebrew', meaning: 'God is my oath', popularity: 285 },
  { name: 'Elisa', slug: 'elisa', gender: 'girl', origin: 'Hebrew', meaning: 'God is my oath', popularity: 345 },
  { name: 'Elliot', slug: 'elliot-girl', gender: 'girl', origin: 'Hebrew', meaning: 'The Lord is my God', popularity: 425 },
  { name: 'Ellis', slug: 'ellis-girl', gender: 'girl', origin: 'Welsh', meaning: 'Benevolent', popularity: 385 },
  { name: 'Elodie', slug: 'elodie', gender: 'girl', origin: 'French', meaning: 'Marsh flower', popularity: 275 },
  { name: 'Elsa', slug: 'elsa', gender: 'girl', origin: 'German', meaning: 'Pledged to God', popularity: 285 },
  { name: 'Emelia', slug: 'emelia', gender: 'girl', origin: 'Latin', meaning: 'Rival', popularity: 265 },
  { name: 'Emersyn', slug: 'emersyn', gender: 'girl', origin: 'English', meaning: 'Brave, powerful', popularity: 115 },
  { name: 'Emmalyn', slug: 'emmalyn', gender: 'girl', origin: 'German', meaning: 'Peaceful home', popularity: 345 },
  { name: 'Emmie', slug: 'emmie', gender: 'girl', origin: 'German', meaning: 'Universal', popularity: 385 },
  { name: 'Emmy', slug: 'emmy', gender: 'girl', origin: 'German', meaning: 'Universal', popularity: 285 },
  { name: 'Ensley', slug: 'ensley', gender: 'girl', origin: 'English', meaning: 'One\'s own meadow', popularity: 345 },
  { name: 'Erica', slug: 'erica', gender: 'girl', origin: 'Norse', meaning: 'Eternal ruler', popularity: 425 },
  { name: 'Esmeralda', slug: 'esmeralda', gender: 'girl', origin: 'Spanish', meaning: 'Emerald', popularity: 285 },
  { name: 'Esperanza', slug: 'esperanza', gender: 'girl', origin: 'Spanish', meaning: 'Hope', popularity: 465 },
  { name: 'Estella', slug: 'estella', gender: 'girl', origin: 'Latin', meaning: 'Star', popularity: 345 },
  { name: 'Estelle', slug: 'estelle', gender: 'girl', origin: 'French', meaning: 'Star', popularity: 385 },
  { name: 'Estrella', slug: 'estrella', gender: 'girl', origin: 'Spanish', meaning: 'Star', popularity: 398 },
  { name: 'Etta', slug: 'etta', gender: 'girl', origin: 'English', meaning: 'Ruler of the home', popularity: 485 },
  { name: 'Evangeline', slug: 'evangeline', gender: 'girl', origin: 'Greek', meaning: 'Bearer of good news', popularity: 205 },
  { name: 'Everlee', slug: 'everlee', gender: 'girl', origin: 'English', meaning: 'Wild boar meadow', popularity: 185 },
  { name: 'Everleigh', slug: 'everleigh', gender: 'girl', origin: 'English', meaning: 'Wild boar meadow', popularity: 125 },
  // F names
  { name: 'Fallon', slug: 'fallon', gender: 'girl', origin: 'Irish', meaning: 'Leader', popularity: 445 },
  { name: 'Farrah', slug: 'farrah', gender: 'girl', origin: 'Arabic', meaning: 'Joy', popularity: 485 },
  { name: 'Fernanda', slug: 'fernanda', gender: 'girl', origin: 'Spanish', meaning: 'Adventurous journey', popularity: 385 },
  { name: 'Finley', slug: 'finley-girl', gender: 'girl', origin: 'Irish', meaning: 'Fair warrior', popularity: 175 },
  { name: 'Fiona', slug: 'fiona', gender: 'girl', origin: 'Irish', meaning: 'Fair, white', popularity: 265 },
  { name: 'Frances', slug: 'frances', gender: 'girl', origin: 'Latin', meaning: 'From France', popularity: 385 },
  { name: 'Francine', slug: 'francine', gender: 'girl', origin: 'French', meaning: 'From France', popularity: 525 },
  // G names
  { name: 'Gabrielle', slug: 'gabrielle', gender: 'girl', origin: 'Hebrew', meaning: 'God is my strength', popularity: 185 },
  { name: 'Galilea', slug: 'galilea', gender: 'girl', origin: 'Hebrew', meaning: 'From Galilee', popularity: 425 },
  { name: 'Gemma', slug: 'gemma', gender: 'girl', origin: 'Italian', meaning: 'Precious stone', popularity: 158 },
  { name: 'Giana', slug: 'giana', gender: 'girl', origin: 'Italian', meaning: 'God is gracious', popularity: 345 },
  { name: 'Giavanna', slug: 'giavanna', gender: 'girl', origin: 'Italian', meaning: 'God is gracious', popularity: 485 },
  { name: 'Gillian', slug: 'gillian', gender: 'girl', origin: 'Latin', meaning: 'Youthful', popularity: 485 },
  { name: 'Giovanna', slug: 'giovanna', gender: 'girl', origin: 'Italian', meaning: 'God is gracious', popularity: 315 },
  { name: 'Giuliana', slug: 'giuliana', gender: 'girl', origin: 'Italian', meaning: 'Youthful', popularity: 345 },
  { name: 'Gracelyn', slug: 'gracelyn', gender: 'girl', origin: 'English', meaning: 'Grace lake', popularity: 285 },
  { name: 'Gracelynn', slug: 'gracelynn', gender: 'girl', origin: 'English', meaning: 'Grace lake', popularity: 325 },
  { name: 'Greta', slug: 'greta', gender: 'girl', origin: 'German', meaning: 'Pearl', popularity: 412 },
  { name: 'Guadalupe', slug: 'guadalupe', gender: 'girl', origin: 'Spanish', meaning: 'Valley of wolves', popularity: 385 },
  { name: 'Guinevere', slug: 'guinevere', gender: 'girl', origin: 'Welsh', meaning: 'White phantom', popularity: 512 },
  // H names
  { name: 'Haisley', slug: 'haisley', gender: 'girl', origin: 'English', meaning: 'Hazel meadow', popularity: 285 },
  { name: 'Halle', slug: 'halle', gender: 'girl', origin: 'Norse', meaning: 'Heroine', popularity: 345 },
  { name: 'Hallie', slug: 'hallie', gender: 'girl', origin: 'English', meaning: 'Dweller at the hall', popularity: 285 },
  { name: 'Hana', slug: 'hana', gender: 'girl', origin: 'Japanese', meaning: 'Flower', popularity: 398 },
  { name: 'Hanna', slug: 'hanna', gender: 'girl', origin: 'Hebrew', meaning: 'Grace', popularity: 285 },
  { name: 'Harlee', slug: 'harlee', gender: 'girl', origin: 'English', meaning: 'Hare meadow', popularity: 325 },
  { name: 'Harley', slug: 'harley-girl', gender: 'girl', origin: 'English', meaning: 'Hare meadow', popularity: 145 },
  { name: 'Harmoni', slug: 'harmoni', gender: 'girl', origin: 'English', meaning: 'Unity, peace', popularity: 425 },
  { name: 'Haven', slug: 'haven', gender: 'girl', origin: 'English', meaning: 'Safe place', popularity: 178 },
  { name: 'Haylee', slug: 'haylee', gender: 'girl', origin: 'English', meaning: 'Hay meadow', popularity: 285 },
  { name: 'Hayley', slug: 'hayley', gender: 'girl', origin: 'English', meaning: 'Hay meadow', popularity: 325 },
  { name: 'Hayleigh', slug: 'hayleigh', gender: 'girl', origin: 'English', meaning: 'Hay meadow', popularity: 425 },
  { name: 'Heather', slug: 'heather', gender: 'girl', origin: 'English', meaning: 'Heather flower', popularity: 385 },
  { name: 'Heaven', slug: 'heaven', gender: 'girl', origin: 'English', meaning: 'Paradise', popularity: 312 },
  { name: 'Helen', slug: 'helen', gender: 'girl', origin: 'Greek', meaning: 'Bright, shining', popularity: 385 },
  { name: 'Henley', slug: 'henley', gender: 'girl', origin: 'English', meaning: 'High meadow', popularity: 185 },
  { name: 'Holland', slug: 'holland', gender: 'girl', origin: 'Dutch', meaning: 'Woodland', popularity: 425 },
  // I names
  { name: 'Iliana', slug: 'iliana', gender: 'girl', origin: 'Greek', meaning: 'Bright', popularity: 398 },
  { name: 'Imani', slug: 'imani', gender: 'girl', origin: 'Swahili', meaning: 'Faith', popularity: 345 },
  { name: 'Ines', slug: 'ines', gender: 'girl', origin: 'Spanish', meaning: 'Pure, holy', popularity: 485 },
  { name: 'Ingrid', slug: 'ingrid', gender: 'girl', origin: 'Norse', meaning: 'Beautiful', popularity: 485 },
  { name: 'Irene', slug: 'irene', gender: 'girl', origin: 'Greek', meaning: 'Peace', popularity: 385 },
  { name: 'Isa', slug: 'isa', gender: 'girl', origin: 'German', meaning: 'Iron-willed', popularity: 485 },
  { name: 'Isabela', slug: 'isabela', gender: 'girl', origin: 'Spanish', meaning: 'Devoted to God', popularity: 145 },
  { name: 'Isadora', slug: 'isadora', gender: 'girl', origin: 'Greek', meaning: 'Gift of Isis', popularity: 512 },
  { name: 'Isis', slug: 'isis', gender: 'girl', origin: 'Egyptian', meaning: 'Throne', popularity: 485 },
  { name: 'Ivette', slug: 'ivette', gender: 'girl', origin: 'French', meaning: 'Yew wood', popularity: 512 },
  { name: 'Ivory', slug: 'ivory', gender: 'girl', origin: 'English', meaning: 'White, pure', popularity: 285 },
  { name: 'Izabella', slug: 'izabella', gender: 'girl', origin: 'Hebrew', meaning: 'Devoted to God', popularity: 225 },
  // J names
  { name: 'Jaelyn', slug: 'jaelyn', gender: 'girl', origin: 'American', meaning: 'Supplanter', popularity: 345 },
  { name: 'Jaliyah', slug: 'jaliyah', gender: 'girl', origin: 'Arabic', meaning: 'Exalted', popularity: 412 },
  { name: 'Jamie', slug: 'jamie-girl', gender: 'girl', origin: 'Hebrew', meaning: 'Supplanter', popularity: 385 },
  { name: 'Janelle', slug: 'janelle', gender: 'girl', origin: 'French', meaning: 'God is gracious', popularity: 485 },
  { name: 'Janessa', slug: 'janessa', gender: 'girl', origin: 'American', meaning: 'God is gracious', popularity: 512 },
  { name: 'Jayla', slug: 'jayla', gender: 'girl', origin: 'American', meaning: 'Blue jay bird', popularity: 165 },
  { name: 'Jaylah', slug: 'jaylah', gender: 'girl', origin: 'American', meaning: 'Supplanter', popularity: 345 },
  { name: 'Jayleen', slug: 'jayleen', gender: 'girl', origin: 'American', meaning: 'Jay bird', popularity: 385 },
  { name: 'Jaylene', slug: 'jaylene', gender: 'girl', origin: 'American', meaning: 'Jay bird', popularity: 425 },
  { name: 'Jazlyn', slug: 'jazlyn', gender: 'girl', origin: 'American', meaning: 'Jasmine flower', popularity: 385 },
  { name: 'Jazmin', slug: 'jazmin', gender: 'girl', origin: 'Persian', meaning: 'Jasmine flower', popularity: 345 },
  { name: 'Jean', slug: 'jean', gender: 'girl', origin: 'French', meaning: 'God is gracious', popularity: 485 },
  { name: 'Jemma', slug: 'jemma', gender: 'girl', origin: 'Italian', meaning: 'Precious stone', popularity: 398 },
  { name: 'Jenna', slug: 'jenna', gender: 'girl', origin: 'Welsh', meaning: 'Fair one', popularity: 312 },
  { name: 'Jenny', slug: 'jenny', gender: 'girl', origin: 'Welsh', meaning: 'Fair one', popularity: 425 },
  { name: 'Jessie', slug: 'jessie-girl', gender: 'girl', origin: 'Hebrew', meaning: 'God beholds', popularity: 385 },
  { name: 'Jewel', slug: 'jewel', gender: 'girl', origin: 'English', meaning: 'Precious stone', popularity: 485 },
  { name: 'Jillian', slug: 'jillian', gender: 'girl', origin: 'Latin', meaning: 'Youthful', popularity: 385 },
  { name: 'Jimena', slug: 'jimena', gender: 'girl', origin: 'Spanish', meaning: 'Listener', popularity: 312 },
  { name: 'Joan', slug: 'joan', gender: 'girl', origin: 'Hebrew', meaning: 'God is gracious', popularity: 512 },
  { name: 'Joanna', slug: 'joanna', gender: 'girl', origin: 'Hebrew', meaning: 'God is gracious', popularity: 325 },
  { name: 'Jocelyn', slug: 'jocelyn', gender: 'girl', origin: 'German', meaning: 'Member of Gauts', popularity: 215 },
  { name: 'Joelle', slug: 'joelle', gender: 'girl', origin: 'French', meaning: 'Jehovah is God', popularity: 425 },
  { name: 'Johanna', slug: 'johanna', gender: 'girl', origin: 'German', meaning: 'God is gracious', popularity: 385 },
  { name: 'Jolene', slug: 'jolene', gender: 'girl', origin: 'American', meaning: 'Pretty', popularity: 425 },
  { name: 'Jolie', slug: 'jolie', gender: 'girl', origin: 'French', meaning: 'Pretty', popularity: 312 },
  { name: 'Jordyn', slug: 'jordyn', gender: 'girl', origin: 'Hebrew', meaning: 'Flowing down', popularity: 225 },
  { name: 'Joselyn', slug: 'joselyn', gender: 'girl', origin: 'German', meaning: 'Member of Gauts', popularity: 385 },
  { name: 'Joy', slug: 'joy', gender: 'girl', origin: 'English', meaning: 'Happiness', popularity: 312 },
  { name: 'Joyce', slug: 'joyce', gender: 'girl', origin: 'Latin', meaning: 'Lord', popularity: 485 },
  { name: 'Judith', slug: 'judith', gender: 'girl', origin: 'Hebrew', meaning: 'Woman from Judea', popularity: 485 },
  { name: 'Julianne', slug: 'julianne', gender: 'girl', origin: 'Latin', meaning: 'Youthful', popularity: 385 },
  { name: 'Julie', slug: 'julie', gender: 'girl', origin: 'French', meaning: 'Youthful', popularity: 365 },
  { name: 'Julieta', slug: 'julieta', gender: 'girl', origin: 'Spanish', meaning: 'Youthful', popularity: 265 },
  { name: 'Juliette', slug: 'juliette', gender: 'girl', origin: 'French', meaning: 'Youthful', popularity: 145 },
  { name: 'Juniper', slug: 'juniper', gender: 'girl', origin: 'Latin', meaning: 'Juniper tree', popularity: 172 },
  { name: 'Justice', slug: 'justice-girl', gender: 'girl', origin: 'English', meaning: 'Fairness, righteousness', popularity: 345 },
  // K names
  { name: 'Kadence', slug: 'kadence', gender: 'girl', origin: 'Latin', meaning: 'Rhythm', popularity: 345 },
  { name: 'Kaia', slug: 'kaia', gender: 'girl', origin: 'Scandinavian', meaning: 'Pure', popularity: 165 },
  { name: 'Kailee', slug: 'kailee', gender: 'girl', origin: 'American', meaning: 'Pure', popularity: 385 },
  { name: 'Kailyn', slug: 'kailyn', gender: 'girl', origin: 'American', meaning: 'Pure', popularity: 385 },
  { name: 'Kalani', slug: 'kalani', gender: 'girl', origin: 'Hawaiian', meaning: 'The heavens', popularity: 285 },
  { name: 'Kaleigh', slug: 'kaleigh', gender: 'girl', origin: 'Irish', meaning: 'Slender', popularity: 398 },
  { name: 'Kallie', slug: 'kallie', gender: 'girl', origin: 'Greek', meaning: 'Beautiful', popularity: 385 },
  { name: 'Kamari', slug: 'kamari-girl', gender: 'girl', origin: 'Swahili', meaning: 'Moonlight', popularity: 425 },
  { name: 'Kamryn', slug: 'kamryn', gender: 'girl', origin: 'Scottish', meaning: 'Crooked nose', popularity: 345 },
  { name: 'Karen', slug: 'karen', gender: 'girl', origin: 'Danish', meaning: 'Pure', popularity: 512 },
  { name: 'Karla', slug: 'karla', gender: 'girl', origin: 'German', meaning: 'Free woman', popularity: 425 },
  { name: 'Karsyn', slug: 'karsyn', gender: 'girl', origin: 'American', meaning: 'Son of marsh dwellers', popularity: 425 },
  { name: 'Kate', slug: 'kate', gender: 'girl', origin: 'Greek', meaning: 'Pure', popularity: 285 },
  { name: 'Katelyn', slug: 'katelyn', gender: 'girl', origin: 'Irish', meaning: 'Pure', popularity: 285 },
  { name: 'Katharine', slug: 'katharine', gender: 'girl', origin: 'Greek', meaning: 'Pure', popularity: 485 },
  { name: 'Kaylani', slug: 'kaylani', gender: 'girl', origin: 'Hawaiian', meaning: 'Sea and sky', popularity: 285 },
  { name: 'Kaylie', slug: 'kaylie', gender: 'girl', origin: 'American', meaning: 'Pure', popularity: 365 },
  { name: 'Kaylin', slug: 'kaylin', gender: 'girl', origin: 'Irish', meaning: 'Slender', popularity: 385 },
  { name: 'Kehlani', slug: 'kehlani', gender: 'girl', origin: 'Hawaiian', meaning: 'Sea and sky', popularity: 285 },
  { name: 'Keily', slug: 'keily', gender: 'girl', origin: 'Irish', meaning: 'Slender', popularity: 512 },
  { name: 'Keira', slug: 'keira', gender: 'girl', origin: 'Irish', meaning: 'Dark-haired', popularity: 258 },
  { name: 'Kenley', slug: 'kenley', gender: 'girl', origin: 'English', meaning: 'Royal meadow', popularity: 285 },
  { name: 'Kenna', slug: 'kenna', gender: 'girl', origin: 'Irish', meaning: 'Born of fire', popularity: 385 },
  { name: 'Kennedi', slug: 'kennedi', gender: 'girl', origin: 'Irish', meaning: 'Helmeted chief', popularity: 345 },
  { name: 'Kenzie', slug: 'kenzie', gender: 'girl', origin: 'Scottish', meaning: 'Fair one', popularity: 285 },
  { name: 'Kiera', slug: 'kiera', gender: 'girl', origin: 'Irish', meaning: 'Dark-haired', popularity: 398 },
  { name: 'Kimber', slug: 'kimber', gender: 'girl', origin: 'English', meaning: 'Royal fortress', popularity: 412 },
  { name: 'Kimora', slug: 'kimora', gender: 'girl', origin: 'Japanese', meaning: 'Village of the wood', popularity: 512 },
  { name: 'Kinley', slug: 'kinley', gender: 'girl', origin: 'Irish', meaning: 'Fair hero', popularity: 178 },
  { name: 'Kinslee', slug: 'kinslee', gender: 'girl', origin: 'English', meaning: 'King\'s meadow', popularity: 285 },
  { name: 'Kinsley', slug: 'kinsley', gender: 'girl', origin: 'English', meaning: 'King\'s meadow', popularity: 59 },
  { name: 'Kiara', slug: 'kiara', gender: 'girl', origin: 'Irish', meaning: 'Dark', popularity: 178 },
  { name: 'Kirsten', slug: 'kirsten', gender: 'girl', origin: 'Scandinavian', meaning: 'Christian', popularity: 512 },
  { name: 'Kora', slug: 'kora', gender: 'girl', origin: 'Greek', meaning: 'Maiden', popularity: 345 },
  { name: 'Kristen', slug: 'kristen', gender: 'girl', origin: 'Scandinavian', meaning: 'Christian', popularity: 425 },
  { name: 'Kristina', slug: 'kristina', gender: 'girl', origin: 'Scandinavian', meaning: 'Christian', popularity: 485 },
  { name: 'Kyla', slug: 'kyla', gender: 'girl', origin: 'Gaelic', meaning: 'Narrow strait', popularity: 425 },
  { name: 'Kyleigh', slug: 'kyleigh', gender: 'girl', origin: 'Irish', meaning: 'Narrow strait', popularity: 345 },
  { name: 'Kyra', slug: 'kyra', gender: 'girl', origin: 'Greek', meaning: 'Lady', popularity: 285 },
  // L names
  { name: 'Lacey', slug: 'lacey', gender: 'girl', origin: 'French', meaning: 'From Lacy', popularity: 385 },
  { name: 'Laila', slug: 'laila', gender: 'girl', origin: 'Arabic', meaning: 'Night', popularity: 58 },
  { name: 'Lainey', slug: 'lainey', gender: 'girl', origin: 'English', meaning: 'Bright light', popularity: 225 },
  { name: 'Lana', slug: 'lana', gender: 'girl', origin: 'Slavic', meaning: 'Light', popularity: 315 },
  { name: 'Landry', slug: 'landry', gender: 'girl', origin: 'English', meaning: 'Ruler', popularity: 412 },
  { name: 'Larissa', slug: 'larissa', gender: 'girl', origin: 'Greek', meaning: 'Citadel', popularity: 485 },
  { name: 'Laura', slug: 'laura', gender: 'girl', origin: 'Latin', meaning: 'Laurel', popularity: 225 },
  { name: 'Laurel', slug: 'laurel', gender: 'girl', origin: 'Latin', meaning: 'Laurel tree', popularity: 385 },
  { name: 'Layla', slug: 'layla', gender: 'girl', origin: 'Arabic', meaning: 'Night, dark beauty', popularity: 26 },
  { name: 'Laylani', slug: 'laylani', gender: 'girl', origin: 'Hawaiian', meaning: 'Heavenly flower', popularity: 398 },
  { name: 'Lea', slug: 'lea', gender: 'girl', origin: 'Hebrew', meaning: 'Weary', popularity: 425 },
  { name: 'Leanna', slug: 'leanna', gender: 'girl', origin: 'English', meaning: 'Vine', popularity: 485 },
  { name: 'Legacy', slug: 'legacy', gender: 'girl', origin: 'English', meaning: 'Inheritance', popularity: 345 },
  { name: 'Leighton', slug: 'leighton', gender: 'girl', origin: 'English', meaning: 'Meadow town', popularity: 285 },
  { name: 'Lena', slug: 'lena', gender: 'girl', origin: 'Greek', meaning: 'Light', popularity: 182 },
  { name: 'Lennon', slug: 'lennon-girl', gender: 'girl', origin: 'Irish', meaning: 'Little cloak', popularity: 285 },
  { name: 'Lennox', slug: 'lennox-girl', gender: 'girl', origin: 'Scottish', meaning: 'Elm grove', popularity: 398 },
  { name: 'Leona', slug: 'leona', gender: 'girl', origin: 'Latin', meaning: 'Lioness', popularity: 312 },
  { name: 'Leonora', slug: 'leonora', gender: 'girl', origin: 'Greek', meaning: 'Light', popularity: 512 },
  { name: 'Leslie', slug: 'leslie', gender: 'girl', origin: 'Scottish', meaning: 'Holly garden', popularity: 328 },
  { name: 'Lexi', slug: 'lexi', gender: 'girl', origin: 'Greek', meaning: 'Defender', popularity: 325 },
  { name: 'Lexie', slug: 'lexie', gender: 'girl', origin: 'Greek', meaning: 'Defender', popularity: 385 },
  { name: 'Leyla', slug: 'leyla', gender: 'girl', origin: 'Arabic', meaning: 'Night', popularity: 285 },
  { name: 'Lia', slug: 'lia', gender: 'girl', origin: 'Italian', meaning: 'Bearer of good news', popularity: 225 },
  { name: 'Liana', slug: 'liana', gender: 'girl', origin: 'French', meaning: 'To bind, vine', popularity: 325 },
  { name: 'Liberty', slug: 'liberty', gender: 'girl', origin: 'English', meaning: 'Freedom', popularity: 398 },
  { name: 'Liesel', slug: 'liesel', gender: 'girl', origin: 'German', meaning: 'God is my oath', popularity: 512 },
  { name: 'Lilah', slug: 'lilah', gender: 'girl', origin: 'Arabic', meaning: 'Night', popularity: 185 },
  { name: 'Lilian', slug: 'lilian', gender: 'girl', origin: 'Latin', meaning: 'Lily flower', popularity: 285 },
  { name: 'Lilith', slug: 'lilith', gender: 'girl', origin: 'Hebrew', meaning: 'Night monster', popularity: 325 },
  { name: 'Lilliana', slug: 'lilliana', gender: 'girl', origin: 'Latin', meaning: 'Lily flower', popularity: 145 },
  { name: 'Lina', slug: 'lina', gender: 'girl', origin: 'Arabic', meaning: 'Tender', popularity: 285 },
  { name: 'Linda', slug: 'linda', gender: 'girl', origin: 'Spanish', meaning: 'Beautiful', popularity: 512 },
  { name: 'Lindsey', slug: 'lindsey', gender: 'girl', origin: 'English', meaning: 'Lincoln\'s wetland', popularity: 485 },
  { name: 'Lisa', slug: 'lisa', gender: 'girl', origin: 'Hebrew', meaning: 'God is my oath', popularity: 512 },
  { name: 'Liv', slug: 'liv', gender: 'girl', origin: 'Norse', meaning: 'Life', popularity: 425 },
  { name: 'Livia', slug: 'livia', gender: 'girl', origin: 'Latin', meaning: 'Blue', popularity: 312 },
  { name: 'Lola', slug: 'lola', gender: 'girl', origin: 'Spanish', meaning: 'Sorrows', popularity: 198 },
  { name: 'Londyn', slug: 'londyn', gender: 'girl', origin: 'English', meaning: 'From London', popularity: 142 },
  { name: 'Lorelai', slug: 'lorelai', gender: 'girl', origin: 'German', meaning: 'Alluring rock', popularity: 285 },
  { name: 'Louisa', slug: 'louisa', gender: 'girl', origin: 'German', meaning: 'Famous warrior', popularity: 512 },
  { name: 'Louise', slug: 'louise', gender: 'girl', origin: 'German', meaning: 'Famous warrior', popularity: 485 },
  { name: 'Luciana', slug: 'luciana', gender: 'girl', origin: 'Italian', meaning: 'Light', popularity: 245 },
  { name: 'Lucille', slug: 'lucille', gender: 'girl', origin: 'French', meaning: 'Light', popularity: 385 },
  { name: 'Luella', slug: 'luella', gender: 'girl', origin: 'English', meaning: 'Famous warrior', popularity: 425 },
  { name: 'Luisa', slug: 'luisa', gender: 'girl', origin: 'Spanish', meaning: 'Famous warrior', popularity: 485 },
  { name: 'Luz', slug: 'luz', gender: 'girl', origin: 'Spanish', meaning: 'Light', popularity: 485 },
  { name: 'Lyanna', slug: 'lyanna', gender: 'girl', origin: 'Hebrew', meaning: 'God has answered', popularity: 445 },
  { name: 'Lyla', slug: 'lyla', gender: 'girl', origin: 'Arabic', meaning: 'Night', popularity: 68 },
  { name: 'Lylah', slug: 'lylah', gender: 'girl', origin: 'Arabic', meaning: 'Night', popularity: 285 },
  { name: 'Lynette', slug: 'lynette', gender: 'girl', origin: 'Welsh', meaning: 'Idol', popularity: 512 },
  { name: 'Lynn', slug: 'lynn', gender: 'girl', origin: 'Welsh', meaning: 'Lake', popularity: 485 },
];

// Additional boy names to add
const additionalBoyNames = [
  // A names
  { name: 'Aaron', slug: 'aaron', gender: 'boy', origin: 'Hebrew', meaning: 'High mountain', popularity: 62 },
  { name: 'Abel', slug: 'abel', gender: 'boy', origin: 'Hebrew', meaning: 'Breath', popularity: 155 },
  { name: 'Abraham', slug: 'abraham', gender: 'boy', origin: 'Hebrew', meaning: 'Father of multitudes', popularity: 178 },
  { name: 'Ace', slug: 'ace', gender: 'boy', origin: 'Latin', meaning: 'One, unity', popularity: 165 },
  { name: 'Adam', slug: 'adam', gender: 'boy', origin: 'Hebrew', meaning: 'Man, earth', popularity: 95 },
  { name: 'Aden', slug: 'aden', gender: 'boy', origin: 'Irish', meaning: 'Little fire', popularity: 285 },
  { name: 'Adrian', slug: 'adrian', gender: 'boy', origin: 'Latin', meaning: 'From Hadria', popularity: 55 },
  { name: 'Aidan', slug: 'aidan', gender: 'boy', origin: 'Irish', meaning: 'Little fire', popularity: 168 },
  { name: 'Alan', slug: 'alan', gender: 'boy', origin: 'Celtic', meaning: 'Handsome', popularity: 285 },
  { name: 'Albert', slug: 'albert', gender: 'boy', origin: 'German', meaning: 'Noble, bright', popularity: 285 },
  { name: 'Aldo', slug: 'aldo', gender: 'boy', origin: 'German', meaning: 'Old, wise', popularity: 485 },
  { name: 'Alec', slug: 'alec', gender: 'boy', origin: 'Greek', meaning: 'Defender', popularity: 325 },
  { name: 'Alejandro', slug: 'alejandro', gender: 'boy', origin: 'Spanish', meaning: 'Defender', popularity: 152 },
  { name: 'Alessandro', slug: 'alessandro', gender: 'boy', origin: 'Italian', meaning: 'Defender', popularity: 345 },
  { name: 'Alex', slug: 'alex', gender: 'boy', origin: 'Greek', meaning: 'Defender', popularity: 145 },
  { name: 'Alexander', slug: 'alexander', gender: 'boy', origin: 'Greek', meaning: 'Defender of the people', popularity: 11 },
  { name: 'Alexis', slug: 'alexis-boy', gender: 'boy', origin: 'Greek', meaning: 'Defender', popularity: 285 },
  { name: 'Alfred', slug: 'alfred', gender: 'boy', origin: 'English', meaning: 'Wise counselor', popularity: 485 },
  { name: 'Ali', slug: 'ali', gender: 'boy', origin: 'Arabic', meaning: 'Exalted, noble', popularity: 285 },
  { name: 'Alonzo', slug: 'alonzo', gender: 'boy', origin: 'Spanish', meaning: 'Noble, ready', popularity: 412 },
  { name: 'Amir', slug: 'amir', gender: 'boy', origin: 'Arabic', meaning: 'Prince', popularity: 98 },
  { name: 'Anderson', slug: 'anderson', gender: 'boy', origin: 'Greek', meaning: 'Son of Andrew', popularity: 245 },
  { name: 'Andre', slug: 'andre', gender: 'boy', origin: 'French', meaning: 'Manly', popularity: 285 },
  { name: 'Andres', slug: 'andres', gender: 'boy', origin: 'Spanish', meaning: 'Manly', popularity: 225 },
  { name: 'Andrew', slug: 'andrew', gender: 'boy', origin: 'Greek', meaning: 'Manly, brave', popularity: 52 },
  { name: 'Angel', slug: 'angel', gender: 'boy', origin: 'Greek', meaning: 'Messenger', popularity: 68 },
  { name: 'Angelo', slug: 'angelo', gender: 'boy', origin: 'Italian', meaning: 'Messenger', popularity: 325 },
  { name: 'Anthony', slug: 'anthony', gender: 'boy', origin: 'Latin', meaning: 'Priceless', popularity: 38 },
  { name: 'Antonio', slug: 'antonio', gender: 'boy', origin: 'Spanish', meaning: 'Priceless', popularity: 115 },
  { name: 'Apollo', slug: 'apollo', gender: 'boy', origin: 'Greek', meaning: 'Destroyer', popularity: 285 },
  { name: 'Archer', slug: 'archer', gender: 'boy', origin: 'English', meaning: 'Bowman', popularity: 145 },
  { name: 'Ari', slug: 'ari', gender: 'boy', origin: 'Hebrew', meaning: 'Lion', popularity: 285 },
  { name: 'Armando', slug: 'armando', gender: 'boy', origin: 'Spanish', meaning: 'Army man', popularity: 425 },
  { name: 'Arthur', slug: 'arthur', gender: 'boy', origin: 'Celtic', meaning: 'Bear', popularity: 175 },
  { name: 'Asher', slug: 'asher', gender: 'boy', origin: 'Hebrew', meaning: 'Happy, blessed', popularity: 22 },
  { name: 'Ashton', slug: 'ashton', gender: 'boy', origin: 'English', meaning: 'Ash tree town', popularity: 178 },
  { name: 'Atlas', slug: 'atlas', gender: 'boy', origin: 'Greek', meaning: 'To carry', popularity: 145 },
  { name: 'August', slug: 'august', gender: 'boy', origin: 'Latin', meaning: 'Great, magnificent', popularity: 105 },
  { name: 'Augustine', slug: 'augustine', gender: 'boy', origin: 'Latin', meaning: 'Great', popularity: 485 },
  { name: 'Augustus', slug: 'augustus', gender: 'boy', origin: 'Latin', meaning: 'Great', popularity: 365 },
  { name: 'Austin', slug: 'austin', gender: 'boy', origin: 'Latin', meaning: 'Great, magnificent', popularity: 85 },
  { name: 'Axel', slug: 'axel', gender: 'boy', origin: 'Scandinavian', meaning: 'Father of peace', popularity: 75 },
  { name: 'Ayden', slug: 'ayden', gender: 'boy', origin: 'Irish', meaning: 'Little fire', popularity: 85 },
  // B names
  { name: 'Barrett', slug: 'barrett', gender: 'boy', origin: 'German', meaning: 'Bear strength', popularity: 285 },
  { name: 'Beau', slug: 'beau', gender: 'boy', origin: 'French', meaning: 'Handsome', popularity: 125 },
  { name: 'Beckett', slug: 'beckett', gender: 'boy', origin: 'English', meaning: 'Bee cottage', popularity: 115 },
  { name: 'Benjamin', slug: 'benjamin', gender: 'boy', origin: 'Hebrew', meaning: 'Son of the right hand', popularity: 6 },
  { name: 'Bennett', slug: 'bennett', gender: 'boy', origin: 'Latin', meaning: 'Blessed', popularity: 85 },
  { name: 'Bentley', slug: 'bentley', gender: 'boy', origin: 'English', meaning: 'Meadow with coarse grass', popularity: 125 },
  { name: 'Blake', slug: 'blake', gender: 'boy', origin: 'English', meaning: 'Dark, fair', popularity: 145 },
  { name: 'Blaze', slug: 'blaze', gender: 'boy', origin: 'Latin', meaning: 'Fire', popularity: 385 },
  { name: 'Bo', slug: 'bo', gender: 'boy', origin: 'Norse', meaning: 'To live', popularity: 385 },
  { name: 'Bobby', slug: 'bobby', gender: 'boy', origin: 'German', meaning: 'Bright fame', popularity: 512 },
  { name: 'Bodhi', slug: 'bodhi', gender: 'boy', origin: 'Sanskrit', meaning: 'Awakening, enlightenment', popularity: 115 },
  { name: 'Boston', slug: 'boston', gender: 'boy', origin: 'English', meaning: 'Town by the woods', popularity: 385 },
  { name: 'Bradley', slug: 'bradley', gender: 'boy', origin: 'English', meaning: 'Broad meadow', popularity: 285 },
  { name: 'Brady', slug: 'brady', gender: 'boy', origin: 'Irish', meaning: 'Spirited one', popularity: 225 },
  { name: 'Braeden', slug: 'braeden', gender: 'boy', origin: 'Irish', meaning: 'Salmon', popularity: 385 },
  { name: 'Brandon', slug: 'brandon', gender: 'boy', origin: 'English', meaning: 'Broom-covered hill', popularity: 145 },
  { name: 'Branson', slug: 'branson', gender: 'boy', origin: 'English', meaning: 'Son of Brand', popularity: 412 },
  { name: 'Brantley', slug: 'brantley', gender: 'boy', origin: 'German', meaning: 'Firebrand', popularity: 225 },
  { name: 'Braxton', slug: 'braxton', gender: 'boy', origin: 'English', meaning: 'Brock\'s town', popularity: 125 },
  { name: 'Brayden', slug: 'brayden', gender: 'boy', origin: 'Irish', meaning: 'Salmon', popularity: 98 },
  { name: 'Braylen', slug: 'braylen', gender: 'boy', origin: 'American', meaning: 'Combination name', popularity: 345 },
  { name: 'Brendan', slug: 'brendan', gender: 'boy', origin: 'Irish', meaning: 'Prince', popularity: 285 },
  { name: 'Brian', slug: 'brian', gender: 'boy', origin: 'Irish', meaning: 'High, noble', popularity: 225 },
  { name: 'Briggs', slug: 'briggs', gender: 'boy', origin: 'English', meaning: 'Bridge', popularity: 385 },
  { name: 'Brock', slug: 'brock', gender: 'boy', origin: 'English', meaning: 'Badger', popularity: 325 },
  { name: 'Brody', slug: 'brody', gender: 'boy', origin: 'Irish', meaning: 'Ditch', popularity: 145 },
  { name: 'Brooks', slug: 'brooks', gender: 'boy', origin: 'English', meaning: 'Stream', popularity: 95 },
  { name: 'Bruce', slug: 'bruce', gender: 'boy', origin: 'Scottish', meaning: 'The willowlands', popularity: 485 },
  { name: 'Bruno', slug: 'bruno', gender: 'boy', origin: 'German', meaning: 'Brown', popularity: 385 },
  { name: 'Bryan', slug: 'bryan', gender: 'boy', origin: 'Irish', meaning: 'High, noble', popularity: 225 },
  { name: 'Bryant', slug: 'bryant', gender: 'boy', origin: 'Irish', meaning: 'High, noble', popularity: 385 },
  { name: 'Bryce', slug: 'bryce', gender: 'boy', origin: 'Celtic', meaning: 'Speckled', popularity: 178 },
  { name: 'Bryson', slug: 'bryson', gender: 'boy', origin: 'Welsh', meaning: 'Son of Brice', popularity: 78 },
  // C names
  { name: 'Caden', slug: 'caden', gender: 'boy', origin: 'Welsh', meaning: 'Spirit of battle', popularity: 145 },
  { name: 'Caiden', slug: 'caiden', gender: 'boy', origin: 'Arabic', meaning: 'Companion', popularity: 168 },
  { name: 'Cain', slug: 'cain', gender: 'boy', origin: 'Hebrew', meaning: 'Acquired', popularity: 485 },
  { name: 'Caleb', slug: 'caleb', gender: 'boy', origin: 'Hebrew', meaning: 'Faithful, devoted', popularity: 51 },
  { name: 'Callum', slug: 'callum', gender: 'boy', origin: 'Scottish', meaning: 'Dove', popularity: 285 },
  { name: 'Calvin', slug: 'calvin', gender: 'boy', origin: 'Latin', meaning: 'Bald', popularity: 145 },
  { name: 'Camden', slug: 'camden', gender: 'boy', origin: 'Scottish', meaning: 'Winding valley', popularity: 85 },
  { name: 'Cameron', slug: 'cameron', gender: 'boy', origin: 'Scottish', meaning: 'Crooked nose', popularity: 78 },
  { name: 'Carl', slug: 'carl', gender: 'boy', origin: 'German', meaning: 'Free man', popularity: 485 },
  { name: 'Carlos', slug: 'carlos', gender: 'boy', origin: 'Spanish', meaning: 'Free man', popularity: 145 },
  { name: 'Carson', slug: 'carson', gender: 'boy', origin: 'Scottish', meaning: 'Son of marsh dwellers', popularity: 85 },
  { name: 'Carter', slug: 'carter', gender: 'boy', origin: 'English', meaning: 'Cart driver', popularity: 25 },
  { name: 'Case', slug: 'case', gender: 'boy', origin: 'Irish', meaning: 'Watchful', popularity: 385 },
  { name: 'Cash', slug: 'cash', gender: 'boy', origin: 'Latin', meaning: 'Hollow', popularity: 145 },
  { name: 'Cason', slug: 'cason', gender: 'boy', origin: 'American', meaning: 'Descendant of the vigilant', popularity: 285 },
  { name: 'Cayden', slug: 'cayden', gender: 'boy', origin: 'American', meaning: 'Spirit of battle', popularity: 285 },
  { name: 'Cayson', slug: 'cayson', gender: 'boy', origin: 'American', meaning: 'Healer', popularity: 345 },
  { name: 'Cesar', slug: 'cesar', gender: 'boy', origin: 'Latin', meaning: 'Head of hair', popularity: 312 },
  { name: 'Chance', slug: 'chance', gender: 'boy', origin: 'English', meaning: 'Fortune, luck', popularity: 285 },
  { name: 'Chandler', slug: 'chandler', gender: 'boy', origin: 'French', meaning: 'Candle maker', popularity: 385 },
  { name: 'Charles', slug: 'charles', gender: 'boy', origin: 'German', meaning: 'Free man', popularity: 52 },
  { name: 'Charlie', slug: 'charlie', gender: 'boy', origin: 'German', meaning: 'Free man', popularity: 185 },
  { name: 'Chase', slug: 'chase', gender: 'boy', origin: 'French', meaning: 'Hunter', popularity: 88 },
  { name: 'Christian', slug: 'christian', gender: 'boy', origin: 'Greek', meaning: 'Follower of Christ', popularity: 42 },
  { name: 'Christopher', slug: 'christopher', gender: 'boy', origin: 'Greek', meaning: 'Bearer of Christ', popularity: 45 },
  { name: 'Clark', slug: 'clark', gender: 'boy', origin: 'English', meaning: 'Clerk, scholar', popularity: 385 },
  { name: 'Clayton', slug: 'clayton', gender: 'boy', origin: 'English', meaning: 'Clay town', popularity: 285 },
  { name: 'Cody', slug: 'cody', gender: 'boy', origin: 'Irish', meaning: 'Helpful', popularity: 285 },
  { name: 'Cohen', slug: 'cohen', gender: 'boy', origin: 'Hebrew', meaning: 'Priest', popularity: 285 },
  { name: 'Colby', slug: 'colby', gender: 'boy', origin: 'Norse', meaning: 'Coal town', popularity: 385 },
  { name: 'Cole', slug: 'cole', gender: 'boy', origin: 'English', meaning: 'Swarthy, coal black', popularity: 145 },
  { name: 'Colin', slug: 'colin', gender: 'boy', origin: 'Irish', meaning: 'Young creature', popularity: 178 },
  { name: 'Collin', slug: 'collin', gender: 'boy', origin: 'Irish', meaning: 'Young creature', popularity: 285 },
  { name: 'Colson', slug: 'colson', gender: 'boy', origin: 'English', meaning: 'Son of Nicholas', popularity: 385 },
  { name: 'Colt', slug: 'colt', gender: 'boy', origin: 'English', meaning: 'Young horse', popularity: 285 },
  { name: 'Colton', slug: 'colton', gender: 'boy', origin: 'English', meaning: 'Coal town', popularity: 85 },
  { name: 'Conner', slug: 'conner', gender: 'boy', origin: 'Irish', meaning: 'Lover of hounds', popularity: 285 },
  { name: 'Connor', slug: 'connor', gender: 'boy', origin: 'Irish', meaning: 'Lover of hounds', popularity: 78 },
  { name: 'Cooper', slug: 'cooper', gender: 'boy', origin: 'English', meaning: 'Barrel maker', popularity: 75 },
  { name: 'Corbin', slug: 'corbin', gender: 'boy', origin: 'Latin', meaning: 'Raven', popularity: 285 },
  { name: 'Corey', slug: 'corey', gender: 'boy', origin: 'Irish', meaning: 'From the hollow', popularity: 385 },
  { name: 'Craig', slug: 'craig', gender: 'boy', origin: 'Scottish', meaning: 'Rock', popularity: 512 },
  { name: 'Crew', slug: 'crew', gender: 'boy', origin: 'English', meaning: 'Chariot', popularity: 285 },
  { name: 'Cristian', slug: 'cristian', gender: 'boy', origin: 'Spanish', meaning: 'Follower of Christ', popularity: 285 },
  { name: 'Cruz', slug: 'cruz', gender: 'boy', origin: 'Spanish', meaning: 'Cross', popularity: 185 },
  // D names
  { name: 'Dallas', slug: 'dallas', gender: 'boy', origin: 'Scottish', meaning: 'Meadow dwelling', popularity: 285 },
  { name: 'Dalton', slug: 'dalton', gender: 'boy', origin: 'English', meaning: 'Valley town', popularity: 285 },
  { name: 'Damian', slug: 'damian', gender: 'boy', origin: 'Greek', meaning: 'To tame', popularity: 105 },
  { name: 'Damien', slug: 'damien', gender: 'boy', origin: 'Greek', meaning: 'To tame', popularity: 178 },
  { name: 'Damon', slug: 'damon', gender: 'boy', origin: 'Greek', meaning: 'To tame', popularity: 385 },
  { name: 'Dane', slug: 'dane', gender: 'boy', origin: 'English', meaning: 'From Denmark', popularity: 385 },
  { name: 'Daniel', slug: 'daniel', gender: 'boy', origin: 'Hebrew', meaning: 'God is my judge', popularity: 15 },
  { name: 'Danny', slug: 'danny', gender: 'boy', origin: 'Hebrew', meaning: 'God is my judge', popularity: 385 },
  { name: 'Dante', slug: 'dante', gender: 'boy', origin: 'Italian', meaning: 'Enduring', popularity: 225 },
  { name: 'Darian', slug: 'darian', gender: 'boy', origin: 'Persian', meaning: 'Wealthy', popularity: 485 },
  { name: 'Darius', slug: 'darius', gender: 'boy', origin: 'Persian', meaning: 'Wealthy', popularity: 385 },
  { name: 'Darren', slug: 'darren', gender: 'boy', origin: 'Irish', meaning: 'Great', popularity: 485 },
  { name: 'David', slug: 'david', gender: 'boy', origin: 'Hebrew', meaning: 'Beloved', popularity: 28 },
  { name: 'Davis', slug: 'davis', gender: 'boy', origin: 'English', meaning: 'Son of David', popularity: 285 },
  { name: 'Dawson', slug: 'dawson', gender: 'boy', origin: 'English', meaning: 'Son of David', popularity: 178 },
  { name: 'Dax', slug: 'dax', gender: 'boy', origin: 'French', meaning: 'Water', popularity: 285 },
  { name: 'Daxton', slug: 'daxton', gender: 'boy', origin: 'French', meaning: 'Warrior', popularity: 285 },
  { name: 'Dean', slug: 'dean', gender: 'boy', origin: 'English', meaning: 'Valley', popularity: 178 },
  { name: 'Declan', slug: 'declan', gender: 'boy', origin: 'Irish', meaning: 'Full of goodness', popularity: 78 },
  { name: 'Dennis', slug: 'dennis', gender: 'boy', origin: 'Greek', meaning: 'Devoted to Dionysus', popularity: 512 },
  { name: 'Denver', slug: 'denver', gender: 'boy', origin: 'English', meaning: 'Green valley', popularity: 385 },
  { name: 'Derek', slug: 'derek', gender: 'boy', origin: 'German', meaning: 'Ruler of the people', popularity: 312 },
  { name: 'Desmond', slug: 'desmond', gender: 'boy', origin: 'Irish', meaning: 'South Munster', popularity: 285 },
  { name: 'Devin', slug: 'devin', gender: 'boy', origin: 'Irish', meaning: 'Poet', popularity: 285 },
  { name: 'Diego', slug: 'diego', gender: 'boy', origin: 'Spanish', meaning: 'Supplanter', popularity: 95 },
  { name: 'Dillon', slug: 'dillon', gender: 'boy', origin: 'Irish', meaning: 'Loyal', popularity: 385 },
  { name: 'Dominic', slug: 'dominic', gender: 'boy', origin: 'Latin', meaning: 'Of the Lord', popularity: 85 },
  { name: 'Dominick', slug: 'dominick', gender: 'boy', origin: 'Latin', meaning: 'Of the Lord', popularity: 312 },
  { name: 'Donald', slug: 'donald', gender: 'boy', origin: 'Scottish', meaning: 'World ruler', popularity: 512 },
  { name: 'Donovan', slug: 'donovan', gender: 'boy', origin: 'Irish', meaning: 'Dark warrior', popularity: 285 },
  { name: 'Dorian', slug: 'dorian', gender: 'boy', origin: 'Greek', meaning: 'From Doris', popularity: 385 },
  { name: 'Douglas', slug: 'douglas', gender: 'boy', origin: 'Scottish', meaning: 'Dark stream', popularity: 512 },
  { name: 'Drake', slug: 'drake', gender: 'boy', origin: 'English', meaning: 'Dragon', popularity: 285 },
  { name: 'Drew', slug: 'drew', gender: 'boy', origin: 'Greek', meaning: 'Wise', popularity: 312 },
  { name: 'Duke', slug: 'duke', gender: 'boy', origin: 'Latin', meaning: 'Leader', popularity: 285 },
  { name: 'Duncan', slug: 'duncan', gender: 'boy', origin: 'Scottish', meaning: 'Dark warrior', popularity: 385 },
  { name: 'Dylan', slug: 'dylan', gender: 'boy', origin: 'Welsh', meaning: 'Son of the sea', popularity: 32 },
  // E names
  { name: 'Easton', slug: 'easton', gender: 'boy', origin: 'English', meaning: 'East town', popularity: 62 },
  { name: 'Edgar', slug: 'edgar', gender: 'boy', origin: 'English', meaning: 'Wealthy spear', popularity: 385 },
  { name: 'Edison', slug: 'edison', gender: 'boy', origin: 'English', meaning: 'Son of Edward', popularity: 385 },
  { name: 'Edmund', slug: 'edmund', gender: 'boy', origin: 'English', meaning: 'Wealthy protector', popularity: 512 },
  { name: 'Eduardo', slug: 'eduardo', gender: 'boy', origin: 'Spanish', meaning: 'Wealthy guardian', popularity: 285 },
  { name: 'Edward', slug: 'edward', gender: 'boy', origin: 'English', meaning: 'Wealthy guardian', popularity: 178 },
  { name: 'Edwin', slug: 'edwin', gender: 'boy', origin: 'English', meaning: 'Wealthy friend', popularity: 285 },
  { name: 'Eli', slug: 'eli', gender: 'boy', origin: 'Hebrew', meaning: 'Ascended, uplifted', popularity: 52 },
  { name: 'Elian', slug: 'elian', gender: 'boy', origin: 'Hebrew', meaning: 'My God is Yahweh', popularity: 285 },
  { name: 'Elias', slug: 'elias', gender: 'boy', origin: 'Greek', meaning: 'The Lord is my God', popularity: 42 },
  { name: 'Elijah', slug: 'elijah', gender: 'boy', origin: 'Hebrew', meaning: 'My God is Yahweh', popularity: 4 },
  { name: 'Elliot', slug: 'elliot', gender: 'boy', origin: 'Hebrew', meaning: 'The Lord is my God', popularity: 145 },
  { name: 'Elliott', slug: 'elliott', gender: 'boy', origin: 'Hebrew', meaning: 'The Lord is my God', popularity: 125 },
  { name: 'Ellis', slug: 'ellis', gender: 'boy', origin: 'Welsh', meaning: 'Benevolent', popularity: 285 },
  { name: 'Emanuel', slug: 'emanuel', gender: 'boy', origin: 'Hebrew', meaning: 'God is with us', popularity: 285 },
  { name: 'Emerson', slug: 'emerson', gender: 'boy', origin: 'English', meaning: 'Son of Emery', popularity: 178 },
  { name: 'Emiliano', slug: 'emiliano', gender: 'boy', origin: 'Spanish', meaning: 'Rival', popularity: 145 },
  { name: 'Emilio', slug: 'emilio', gender: 'boy', origin: 'Spanish', meaning: 'Rival', popularity: 225 },
  { name: 'Emmanuel', slug: 'emmanuel', gender: 'boy', origin: 'Hebrew', meaning: 'God is with us', popularity: 145 },
  { name: 'Emmett', slug: 'emmett', gender: 'boy', origin: 'English', meaning: 'Universal', popularity: 105 },
  { name: 'Enrique', slug: 'enrique', gender: 'boy', origin: 'Spanish', meaning: 'Ruler of the home', popularity: 385 },
  { name: 'Enzo', slug: 'enzo', gender: 'boy', origin: 'Italian', meaning: 'Ruler of the home', popularity: 85 },
  { name: 'Eric', slug: 'eric', gender: 'boy', origin: 'Norse', meaning: 'Eternal ruler', popularity: 178 },
  { name: 'Erik', slug: 'erik', gender: 'boy', origin: 'Scandinavian', meaning: 'Eternal ruler', popularity: 312 },
  { name: 'Ethan', slug: 'ethan', gender: 'boy', origin: 'Hebrew', meaning: 'Strong, firm', popularity: 18 },
  { name: 'Eugene', slug: 'eugene', gender: 'boy', origin: 'Greek', meaning: 'Well born', popularity: 512 },
  { name: 'Evan', slug: 'evan', gender: 'boy', origin: 'Welsh', meaning: 'God is gracious', popularity: 105 },
  { name: 'Everett', slug: 'everett', gender: 'boy', origin: 'English', meaning: 'Brave as a wild boar', popularity: 85 },
  { name: 'Ezekiel', slug: 'ezekiel', gender: 'boy', origin: 'Hebrew', meaning: 'God strengthens', popularity: 52 },
  { name: 'Ezra', slug: 'ezra', gender: 'boy', origin: 'Hebrew', meaning: 'Helper', popularity: 35 },
  // F names
  { name: 'Fabian', slug: 'fabian', gender: 'boy', origin: 'Latin', meaning: 'Bean grower', popularity: 385 },
  { name: 'Felix', slug: 'felix', gender: 'boy', origin: 'Latin', meaning: 'Happy, fortunate', popularity: 178 },
  { name: 'Fernando', slug: 'fernando', gender: 'boy', origin: 'Spanish', meaning: 'Adventurous journey', popularity: 285 },
  { name: 'Finley', slug: 'finley-boy', gender: 'boy', origin: 'Irish', meaning: 'Fair warrior', popularity: 145 },
  { name: 'Finn', slug: 'finn', gender: 'boy', origin: 'Irish', meaning: 'Fair', popularity: 78 },
  { name: 'Finnegan', slug: 'finnegan', gender: 'boy', origin: 'Irish', meaning: 'Fair', popularity: 285 },
  { name: 'Fletcher', slug: 'fletcher', gender: 'boy', origin: 'English', meaning: 'Arrow maker', popularity: 385 },
  { name: 'Flynn', slug: 'flynn', gender: 'boy', origin: 'Irish', meaning: 'Son of a red-haired man', popularity: 285 },
  { name: 'Ford', slug: 'ford', gender: 'boy', origin: 'English', meaning: 'River crossing', popularity: 385 },
  { name: 'Forrest', slug: 'forrest', gender: 'boy', origin: 'English', meaning: 'Woodsman', popularity: 512 },
  { name: 'Francis', slug: 'francis', gender: 'boy', origin: 'Latin', meaning: 'Frenchman', popularity: 385 },
  { name: 'Francisco', slug: 'francisco', gender: 'boy', origin: 'Spanish', meaning: 'Frenchman', popularity: 285 },
  { name: 'Frank', slug: 'frank', gender: 'boy', origin: 'German', meaning: 'Free man', popularity: 385 },
  { name: 'Franklin', slug: 'franklin', gender: 'boy', origin: 'English', meaning: 'Free landholder', popularity: 385 },
  { name: 'Frederick', slug: 'frederick', gender: 'boy', origin: 'German', meaning: 'Peaceful ruler', popularity: 385 },
  // G names
  { name: 'Gabriel', slug: 'gabriel', gender: 'boy', origin: 'Hebrew', meaning: 'God is my strength', popularity: 28 },
  { name: 'Gael', slug: 'gael', gender: 'boy', origin: 'Irish', meaning: 'Gaelic', popularity: 178 },
  { name: 'Gage', slug: 'gage', gender: 'boy', origin: 'French', meaning: 'Pledge, oath', popularity: 285 },
  { name: 'Garrett', slug: 'garrett', gender: 'boy', origin: 'Irish', meaning: 'Spear strength', popularity: 312 },
  { name: 'Gary', slug: 'gary', gender: 'boy', origin: 'German', meaning: 'Spear', popularity: 512 },
  { name: 'Gavin', slug: 'gavin', gender: 'boy', origin: 'Welsh', meaning: 'White hawk', popularity: 145 },
  { name: 'George', slug: 'george', gender: 'boy', origin: 'Greek', meaning: 'Farmer', popularity: 125 },
  { name: 'Gerald', slug: 'gerald', gender: 'boy', origin: 'German', meaning: 'Ruler with the spear', popularity: 512 },
  { name: 'Gerardo', slug: 'gerardo', gender: 'boy', origin: 'Spanish', meaning: 'Brave with a spear', popularity: 485 },
  { name: 'Gianni', slug: 'gianni', gender: 'boy', origin: 'Italian', meaning: 'God is gracious', popularity: 285 },
  { name: 'Gideon', slug: 'gideon', gender: 'boy', origin: 'Hebrew', meaning: 'Great warrior', popularity: 285 },
  { name: 'Giovanni', slug: 'giovanni', gender: 'boy', origin: 'Italian', meaning: 'God is gracious', popularity: 145 },
  { name: 'Glenn', slug: 'glenn', gender: 'boy', origin: 'Scottish', meaning: 'Valley', popularity: 512 },
  { name: 'Gordon', slug: 'gordon', gender: 'boy', origin: 'Scottish', meaning: 'Great hill', popularity: 512 },
  { name: 'Grady', slug: 'grady', gender: 'boy', origin: 'Irish', meaning: 'Noble', popularity: 312 },
  { name: 'Graham', slug: 'graham', gender: 'boy', origin: 'Scottish', meaning: 'Gravelly homestead', popularity: 185 },
  { name: 'Grant', slug: 'grant', gender: 'boy', origin: 'Scottish', meaning: 'Great, large', popularity: 225 },
  { name: 'Grayson', slug: 'grayson', gender: 'boy', origin: 'English', meaning: 'Son of the gray-haired one', popularity: 35 },
  { name: 'Gregory', slug: 'gregory', gender: 'boy', origin: 'Greek', meaning: 'Watchful', popularity: 312 },
  { name: 'Grey', slug: 'grey', gender: 'boy', origin: 'English', meaning: 'Gray-haired', popularity: 385 },
  { name: 'Griffin', slug: 'griffin', gender: 'boy', origin: 'Welsh', meaning: 'Strong lord', popularity: 178 },
  { name: 'Greyson', slug: 'greyson', gender: 'boy', origin: 'English', meaning: 'Son of the gray-haired one', popularity: 68 },
  { name: 'Gunner', slug: 'gunner', gender: 'boy', origin: 'Norse', meaning: 'Warrior', popularity: 178 },
  { name: 'Gustavo', slug: 'gustavo', gender: 'boy', origin: 'Spanish', meaning: 'Staff of the gods', popularity: 385 },
  // H names
  { name: 'Hank', slug: 'hank', gender: 'boy', origin: 'German', meaning: 'Ruler of the home', popularity: 385 },
  { name: 'Harley', slug: 'harley', gender: 'boy', origin: 'English', meaning: 'Hare meadow', popularity: 312 },
  { name: 'Harold', slug: 'harold', gender: 'boy', origin: 'Norse', meaning: 'Army ruler', popularity: 512 },
  { name: 'Harrison', slug: 'harrison', gender: 'boy', origin: 'English', meaning: 'Son of Harry', popularity: 105 },
  { name: 'Harry', slug: 'harry', gender: 'boy', origin: 'German', meaning: 'Ruler of the home', popularity: 285 },
  { name: 'Harvey', slug: 'harvey', gender: 'boy', origin: 'French', meaning: 'Battle worthy', popularity: 385 },
  { name: 'Hayes', slug: 'hayes', gender: 'boy', origin: 'English', meaning: 'Hedged area', popularity: 285 },
  { name: 'Heath', slug: 'heath', gender: 'boy', origin: 'English', meaning: 'Heathland dweller', popularity: 512 },
  { name: 'Hector', slug: 'hector', gender: 'boy', origin: 'Greek', meaning: 'Holding fast', popularity: 285 },
  { name: 'Hendrix', slug: 'hendrix', gender: 'boy', origin: 'German', meaning: 'Ruler of the home', popularity: 345 },
  { name: 'Henry', slug: 'henry', gender: 'boy', origin: 'German', meaning: 'Ruler of the home', popularity: 12 },
  { name: 'Holden', slug: 'holden', gender: 'boy', origin: 'English', meaning: 'Hollow valley', popularity: 225 },
  { name: 'Houston', slug: 'houston', gender: 'boy', origin: 'Scottish', meaning: 'Hugh\'s town', popularity: 512 },
  { name: 'Howard', slug: 'howard', gender: 'boy', origin: 'English', meaning: 'Brave heart', popularity: 512 },
  { name: 'Hudson', slug: 'hudson', gender: 'boy', origin: 'English', meaning: 'Hugh\'s son', popularity: 45 },
  { name: 'Hugh', slug: 'hugh', gender: 'boy', origin: 'German', meaning: 'Mind, intellect', popularity: 512 },
  { name: 'Hugo', slug: 'hugo', gender: 'boy', origin: 'German', meaning: 'Mind, intellect', popularity: 145 },
  { name: 'Hunter', slug: 'hunter', gender: 'boy', origin: 'English', meaning: 'One who hunts', popularity: 55 },
];

// Additional unisex names
const additionalUnisexNames = [
  { name: 'Addison', slug: 'addison-unisex', gender: 'unisex', origin: 'English', meaning: 'Son of Adam', popularity: 85 },
  { name: 'Ainsley', slug: 'ainsley-unisex', gender: 'unisex', origin: 'Scottish', meaning: 'One\'s own meadow', popularity: 285 },
  { name: 'Alex', slug: 'alex-unisex', gender: 'unisex', origin: 'Greek', meaning: 'Defender of mankind', popularity: 125 },
  { name: 'Ali', slug: 'ali-unisex', gender: 'unisex', origin: 'Arabic', meaning: 'Noble, sublime', popularity: 285 },
  { name: 'Amari', slug: 'amari-unisex', gender: 'unisex', origin: 'Hebrew', meaning: 'Eternal', popularity: 175 },
  { name: 'Angel', slug: 'angel-unisex', gender: 'unisex', origin: 'Greek', meaning: 'Messenger of God', popularity: 95 },
  { name: 'Ari', slug: 'ari-unisex', gender: 'unisex', origin: 'Hebrew', meaning: 'Lion', popularity: 245 },
  { name: 'Ariel', slug: 'ariel-unisex', gender: 'unisex', origin: 'Hebrew', meaning: 'Lion of God', popularity: 155 },
  { name: 'Armani', slug: 'armani-unisex', gender: 'unisex', origin: 'Italian', meaning: 'Warrior', popularity: 345 },
  { name: 'Ashton', slug: 'ashton-unisex', gender: 'unisex', origin: 'English', meaning: 'Ash tree town', popularity: 175 },
  { name: 'August', slug: 'august-unisex', gender: 'unisex', origin: 'Latin', meaning: 'Great, magnificent', popularity: 145 },
  { name: 'Bailey', slug: 'bailey-unisex', gender: 'unisex', origin: 'English', meaning: 'Bailiff', popularity: 185 },
  { name: 'Bellamy', slug: 'bellamy-unisex', gender: 'unisex', origin: 'French', meaning: 'Beautiful friend', popularity: 385 },
  { name: 'Blair', slug: 'blair-unisex', gender: 'unisex', origin: 'Scottish', meaning: 'Plain, field', popularity: 245 },
  { name: 'Blake', slug: 'blake-unisex', gender: 'unisex', origin: 'English', meaning: 'Fair-haired, dark', popularity: 135 },
  { name: 'Bobby', slug: 'bobby-unisex', gender: 'unisex', origin: 'German', meaning: 'Bright fame', popularity: 385 },
  { name: 'Brooklyn', slug: 'brooklyn-unisex', gender: 'unisex', origin: 'American', meaning: 'Water, stream', popularity: 65 },
  { name: 'Cameron', slug: 'cameron-unisex', gender: 'unisex', origin: 'Scottish', meaning: 'Crooked nose', popularity: 85 },
  { name: 'Campbell', slug: 'campbell', gender: 'unisex', origin: 'Scottish', meaning: 'Crooked mouth', popularity: 385 },
  { name: 'Carey', slug: 'carey', gender: 'unisex', origin: 'Irish', meaning: 'Dark', popularity: 512 },
  { name: 'Casey', slug: 'casey', gender: 'unisex', origin: 'Irish', meaning: 'Watchful', popularity: 225 },
  { name: 'Charlie', slug: 'charlie-unisex', gender: 'unisex', origin: 'German', meaning: 'Free man', popularity: 115 },
  { name: 'Chris', slug: 'chris', gender: 'unisex', origin: 'Greek', meaning: 'Christ-bearer', popularity: 285 },
  { name: 'Corey', slug: 'corey-unisex', gender: 'unisex', origin: 'Irish', meaning: 'From the hollow', popularity: 345 },
  { name: 'Dakota', slug: 'dakota-unisex', gender: 'unisex', origin: 'Native American', meaning: 'Friend, ally', popularity: 225 },
  { name: 'Dallas', slug: 'dallas-unisex', gender: 'unisex', origin: 'Scottish', meaning: 'Meadow dwelling', popularity: 285 },
  { name: 'Dana', slug: 'dana-unisex', gender: 'unisex', origin: 'Hebrew', meaning: 'God is my judge', popularity: 385 },
  { name: 'Devin', slug: 'devin-unisex', gender: 'unisex', origin: 'Irish', meaning: 'Poet', popularity: 285 },
  { name: 'Drew', slug: 'drew-unisex', gender: 'unisex', origin: 'Greek', meaning: 'Wise', popularity: 285 },
  { name: 'Eden', slug: 'eden-unisex', gender: 'unisex', origin: 'Hebrew', meaning: 'Paradise', popularity: 145 },
  { name: 'Elliot', slug: 'elliot-unisex', gender: 'unisex', origin: 'Hebrew', meaning: 'The Lord is my God', popularity: 175 },
  { name: 'Ellis', slug: 'ellis-unisex', gender: 'unisex', origin: 'Welsh', meaning: 'Benevolent', popularity: 285 },
  { name: 'Emerson', slug: 'emerson-unisex', gender: 'unisex', origin: 'English', meaning: 'Son of Emery', popularity: 145 },
  { name: 'Everly', slug: 'everly-unisex', gender: 'unisex', origin: 'English', meaning: 'Wild boar meadow', popularity: 85 },
  { name: 'Ezra', slug: 'ezra-unisex', gender: 'unisex', origin: 'Hebrew', meaning: 'Helper', popularity: 55 },
  { name: 'Finley', slug: 'finley-unisex', gender: 'unisex', origin: 'Irish', meaning: 'Fair warrior', popularity: 100 },
  { name: 'Frankie', slug: 'frankie-unisex', gender: 'unisex', origin: 'American', meaning: 'Free one', popularity: 315 },
  { name: 'Glenn', slug: 'glenn-unisex', gender: 'unisex', origin: 'Scottish', meaning: 'Valley', popularity: 485 },
  { name: 'Gray', slug: 'gray', gender: 'unisex', origin: 'English', meaning: 'Gray-haired', popularity: 385 },
  { name: 'Harley', slug: 'harley-unisex', gender: 'unisex', origin: 'English', meaning: 'Hare meadow', popularity: 145 },
  { name: 'Harper', slug: 'harper-unisex', gender: 'unisex', origin: 'English', meaning: 'Harp player', popularity: 55 },
  { name: 'Hayden', slug: 'hayden-unisex', gender: 'unisex', origin: 'English', meaning: 'Hay valley', popularity: 165 },
  { name: 'Hollis', slug: 'hollis', gender: 'unisex', origin: 'English', meaning: 'Near the holly bushes', popularity: 485 },
  { name: 'Hunter', slug: 'hunter-unisex', gender: 'unisex', origin: 'English', meaning: 'One who hunts', popularity: 75 },
  { name: 'Indie', slug: 'indie', gender: 'unisex', origin: 'American', meaning: 'Independent', popularity: 385 },
  { name: 'Jackie', slug: 'jackie', gender: 'unisex', origin: 'Hebrew', meaning: 'Supplanter', popularity: 425 },
  { name: 'Jaden', slug: 'jaden', gender: 'unisex', origin: 'Hebrew', meaning: 'Thankful', popularity: 185 },
  { name: 'Jamie', slug: 'jamie-unisex', gender: 'unisex', origin: 'Hebrew', meaning: 'Supplanter', popularity: 245 },
  { name: 'Jesse', slug: 'jesse', gender: 'unisex', origin: 'Hebrew', meaning: 'Gift', popularity: 175 },
  { name: 'Jordan', slug: 'jordan-unisex', gender: 'unisex', origin: 'Hebrew', meaning: 'Flowing down', popularity: 75 },
  { name: 'Jules', slug: 'jules', gender: 'unisex', origin: 'French', meaning: 'Youthful', popularity: 385 },
  { name: 'Justice', slug: 'justice-unisex', gender: 'unisex', origin: 'English', meaning: 'Righteousness', popularity: 285 },
  { name: 'Kai', slug: 'kai-unisex', gender: 'unisex', origin: 'Hawaiian', meaning: 'Sea', popularity: 92 },
  { name: 'Kameron', slug: 'kameron', gender: 'unisex', origin: 'Scottish', meaning: 'Crooked nose', popularity: 325 },
  { name: 'Kelly', slug: 'kelly', gender: 'unisex', origin: 'Irish', meaning: 'Warrior', popularity: 345 },
  { name: 'Kendall', slug: 'kendall', gender: 'unisex', origin: 'English', meaning: 'Valley of the River Kent', popularity: 225 },
  { name: 'Kennedy', slug: 'kennedy-unisex', gender: 'unisex', origin: 'Irish', meaning: 'Helmeted chief', popularity: 78 },
  { name: 'Kerry', slug: 'kerry', gender: 'unisex', origin: 'Irish', meaning: 'Dark-haired', popularity: 485 },
  { name: 'Kieran', slug: 'kieran', gender: 'unisex', origin: 'Irish', meaning: 'Dark-haired', popularity: 285 },
  { name: 'Kim', slug: 'kim', gender: 'unisex', origin: 'English', meaning: 'Royal fortress meadow', popularity: 512 },
  { name: 'Kyrie', slug: 'kyrie', gender: 'unisex', origin: 'Greek', meaning: 'Lord', popularity: 285 },
  { name: 'Lake', slug: 'lake', gender: 'unisex', origin: 'English', meaning: 'Body of water', popularity: 385 },
  { name: 'Lane', slug: 'lane-unisex', gender: 'unisex', origin: 'English', meaning: 'Path, roadway', popularity: 225 },
  { name: 'Lee', slug: 'lee', gender: 'unisex', origin: 'English', meaning: 'Meadow', popularity: 385 },
  { name: 'Lennon', slug: 'lennon', gender: 'unisex', origin: 'Irish', meaning: 'Little cloak', popularity: 245 },
  { name: 'Lennox', slug: 'lennox', gender: 'unisex', origin: 'Scottish', meaning: 'Elm grove', popularity: 285 },
  { name: 'Leslie', slug: 'leslie-unisex', gender: 'unisex', origin: 'Scottish', meaning: 'Holly garden', popularity: 345 },
  { name: 'Logan', slug: 'logan-unisex', gender: 'unisex', origin: 'Scottish', meaning: 'Little hollow', popularity: 68 },
  { name: 'London', slug: 'london-unisex', gender: 'unisex', origin: 'English', meaning: 'From London', popularity: 108 },
  { name: 'Marley', slug: 'marley-unisex', gender: 'unisex', origin: 'English', meaning: 'Pleasant seaside meadow', popularity: 178 },
  { name: 'Marlowe', slug: 'marlowe', gender: 'unisex', origin: 'English', meaning: 'Driftwood', popularity: 385 },
  { name: 'Max', slug: 'max', gender: 'unisex', origin: 'Latin', meaning: 'Greatest', popularity: 145 },
  { name: 'Morgan', slug: 'morgan-unisex', gender: 'unisex', origin: 'Welsh', meaning: 'Sea-born', popularity: 140 },
  { name: 'Murphy', slug: 'murphy', gender: 'unisex', origin: 'Irish', meaning: 'Sea warrior', popularity: 485 },
  { name: 'Oakley', slug: 'oakley', gender: 'unisex', origin: 'English', meaning: 'Oak meadow', popularity: 185 },
  { name: 'Ocean', slug: 'ocean', gender: 'unisex', origin: 'English', meaning: 'Large body of water', popularity: 385 },
  { name: 'Onyx', slug: 'onyx', gender: 'unisex', origin: 'Greek', meaning: 'Black gemstone', popularity: 385 },
  { name: 'Paris', slug: 'paris', gender: 'unisex', origin: 'Greek', meaning: 'Wallet', popularity: 285 },
  { name: 'Parker', slug: 'parker-unisex', gender: 'unisex', origin: 'English', meaning: 'Park keeper', popularity: 115 },
  { name: 'Pat', slug: 'pat', gender: 'unisex', origin: 'Latin', meaning: 'Noble', popularity: 512 },
  { name: 'Payton', slug: 'payton-unisex', gender: 'unisex', origin: 'English', meaning: 'Fighting man\'s estate', popularity: 145 },
  { name: 'Peyton', slug: 'peyton-unisex', gender: 'unisex', origin: 'English', meaning: 'Fighting man\'s estate', popularity: 88 },
  { name: 'Phoenix', slug: 'phoenix-unisex', gender: 'unisex', origin: 'Greek', meaning: 'Dark red, mythical bird', popularity: 95 },
  { name: 'Quinn', slug: 'quinn-unisex', gender: 'unisex', origin: 'Irish', meaning: 'Wise, intelligent', popularity: 90 },
  { name: 'Raven', slug: 'raven', gender: 'unisex', origin: 'English', meaning: 'Blackbird', popularity: 385 },
  { name: 'Reagan', slug: 'reagan-unisex', gender: 'unisex', origin: 'Irish', meaning: 'Little king', popularity: 112 },
  { name: 'Reese', slug: 'reese-unisex', gender: 'unisex', origin: 'Welsh', meaning: 'Enthusiasm', popularity: 125 },
  { name: 'Remi', slug: 'remi-unisex', gender: 'unisex', origin: 'French', meaning: 'Oarsman', popularity: 175 },
  { name: 'Riley', slug: 'riley-unisex', gender: 'unisex', origin: 'Irish', meaning: 'Courageous', popularity: 45 },
  { name: 'River', slug: 'river-unisex', gender: 'unisex', origin: 'English', meaning: 'Flowing body of water', popularity: 110 },
  { name: 'Robin', slug: 'robin', gender: 'unisex', origin: 'English', meaning: 'Bright fame', popularity: 385 },
  { name: 'Rory', slug: 'rory-unisex', gender: 'unisex', origin: 'Irish', meaning: 'Red king', popularity: 275 },
  { name: 'Rowan', slug: 'rowan-unisex', gender: 'unisex', origin: 'Irish', meaning: 'Little red-haired one', popularity: 105 },
  { name: 'Royal', slug: 'royal', gender: 'unisex', origin: 'English', meaning: 'Of the king', popularity: 285 },
  { name: 'Ryan', slug: 'ryan-unisex', gender: 'unisex', origin: 'Irish', meaning: 'Little king', popularity: 125 },
  { name: 'Sage', slug: 'sage-unisex', gender: 'unisex', origin: 'Latin', meaning: 'Wise, herb', popularity: 170 },
  { name: 'Sam', slug: 'sam-unisex', gender: 'unisex', origin: 'Hebrew', meaning: 'Heard by God', popularity: 198 },
  { name: 'Santana', slug: 'santana', gender: 'unisex', origin: 'Spanish', meaning: 'Saint Anna', popularity: 485 },
  { name: 'Sawyer', slug: 'sawyer-unisex', gender: 'unisex', origin: 'English', meaning: 'Woodcutter', popularity: 95 },
  { name: 'Scout', slug: 'scout', gender: 'unisex', origin: 'French', meaning: 'To listen', popularity: 385 },
  { name: 'Shawn', slug: 'shawn', gender: 'unisex', origin: 'Irish', meaning: 'God is gracious', popularity: 385 },
  { name: 'Shiloh', slug: 'shiloh', gender: 'unisex', origin: 'Hebrew', meaning: 'Peaceful', popularity: 285 },
  { name: 'Sidney', slug: 'sidney', gender: 'unisex', origin: 'English', meaning: 'Wide meadow', popularity: 425 },
  { name: 'Sky', slug: 'sky', gender: 'unisex', origin: 'English', meaning: 'Sky', popularity: 385 },
  { name: 'Skyler', slug: 'skyler-unisex', gender: 'unisex', origin: 'Dutch', meaning: 'Scholar', popularity: 145 },
  { name: 'Spencer', slug: 'spencer', gender: 'unisex', origin: 'English', meaning: 'Dispenser of provisions', popularity: 285 },
  { name: 'Sterling', slug: 'sterling', gender: 'unisex', origin: 'English', meaning: 'Little star', popularity: 385 },
  { name: 'Stevie', slug: 'stevie', gender: 'unisex', origin: 'Greek', meaning: 'Crown', popularity: 385 },
  { name: 'Sutton', slug: 'sutton', gender: 'unisex', origin: 'English', meaning: 'Southern homestead', popularity: 285 },
  { name: 'Sydney', slug: 'sydney', gender: 'unisex', origin: 'English', meaning: 'Wide island', popularity: 145 },
  { name: 'Tanner', slug: 'tanner', gender: 'unisex', origin: 'English', meaning: 'Leather worker', popularity: 285 },
  { name: 'Tatum', slug: 'tatum-unisex', gender: 'unisex', origin: 'English', meaning: 'Cheerful', popularity: 245 },
  { name: 'Taylor', slug: 'taylor-unisex', gender: 'unisex', origin: 'English', meaning: 'Tailor', popularity: 180 },
  { name: 'Teagan', slug: 'teagan-unisex', gender: 'unisex', origin: 'Irish', meaning: 'Little poet', popularity: 185 },
  { name: 'Terry', slug: 'terry', gender: 'unisex', origin: 'German', meaning: 'Power of the tribe', popularity: 512 },
  { name: 'Toni', slug: 'toni', gender: 'unisex', origin: 'Latin', meaning: 'Priceless', popularity: 512 },
  { name: 'Tracy', slug: 'tracy', gender: 'unisex', origin: 'Irish', meaning: 'Warlike', popularity: 512 },
  { name: 'Trinity', slug: 'trinity-unisex', gender: 'unisex', origin: 'Latin', meaning: 'Triad', popularity: 145 },
  { name: 'Winter', slug: 'winter', gender: 'unisex', origin: 'English', meaning: 'Winter season', popularity: 345 },
  { name: 'Wren', slug: 'wren', gender: 'unisex', origin: 'English', meaning: 'Small bird', popularity: 285 },
  { name: 'Wynne', slug: 'wynne', gender: 'unisex', origin: 'Welsh', meaning: 'Fair, white', popularity: 512 },
  { name: 'Zion', slug: 'zion', gender: 'unisex', origin: 'Hebrew', meaning: 'Highest point', popularity: 185 },
];

// Read the current data file
const dataFilePath = path.join(__dirname, '..', 'lib', 'data.ts');
let content = fs.readFileSync(dataFilePath, 'utf8');

// Find the position just before the closing bracket of the names array
const namesArrayEndIndex = content.indexOf('\n]', content.indexOf('const names: BabyName[]'));

// Prepare the new names to insert
const allNewNames = [...additionalGirlNames, ...additionalBoyNames, ...additionalUnisexNames];
const newNamesStr = allNewNames.map(n => {
  const meaningEscaped = n.meaning.replace(/'/g, "\\'");
  return `  { name: '${n.name}', slug: '${n.slug}', gender: '${n.gender}', origin: '${n.origin}', meaning: '${meaningEscaped}', popularity: ${n.popularity} },`;
}).join('\n');

// Insert the new names before the closing bracket
const newContent = content.slice(0, namesArrayEndIndex) + '\n  // Additional names - expansion to 2000+\n' + newNamesStr + '\n' + content.slice(namesArrayEndIndex);

// Write the updated content
fs.writeFileSync(dataFilePath, newContent, 'utf8');

console.log(`Added ${allNewNames.length} new names to the database`);
console.log(`- Girl names: ${additionalGirlNames.length}`);
console.log(`- Boy names: ${additionalBoyNames.length}`);
console.log(`- Unisex names: ${additionalUnisexNames.length}`);
