// Final batch to reach 2000+ names
const fs = require('fs');
const path = require('path');

const finalGirlNames = [
  { name: 'Aaliyah', slug: 'aaliyah-2', gender: 'girl', origin: 'Arabic', meaning: 'Exalted, noble', popularity: 485 },
  { name: 'Addelyn', slug: 'addelyn', gender: 'girl', origin: 'English', meaning: 'Noble', popularity: 398 },
  { name: 'Addilyn', slug: 'addilyn', gender: 'girl', origin: 'American', meaning: 'Noble', popularity: 345 },
  { name: 'Adley', slug: 'adley', gender: 'girl', origin: 'Hebrew', meaning: 'Just, righteous', popularity: 312 },
  { name: 'Ainhoa', slug: 'ainhoa', gender: 'girl', origin: 'Basque', meaning: 'Virgin Mary', popularity: 512 },
  { name: 'Alaia', slug: 'alaia-2', gender: 'girl', origin: 'Basque', meaning: 'Joyful', popularity: 398 },
  { name: 'Alani', slug: 'alani-2', gender: 'girl', origin: 'Hawaiian', meaning: 'Orange tree', popularity: 345 },
  { name: 'Alejandra', slug: 'alejandra', gender: 'girl', origin: 'Spanish', meaning: 'Defender', popularity: 312 },
  { name: 'Alicia', slug: 'alicia-2', gender: 'girl', origin: 'German', meaning: 'Noble', popularity: 398 },
  { name: 'Allie', slug: 'allie', gender: 'girl', origin: 'English', meaning: 'Noble', popularity: 345 },
  { name: 'Alyssa', slug: 'alyssa-2', gender: 'girl', origin: 'Greek', meaning: 'Noble', popularity: 312 },
  { name: 'Amani', slug: 'amani', gender: 'girl', origin: 'Arabic', meaning: 'Wishes', popularity: 398 },
  { name: 'Amelie', slug: 'amelie-2', gender: 'girl', origin: 'French', meaning: 'Hardworking', popularity: 425 },
  { name: 'Amina', slug: 'amina', gender: 'girl', origin: 'Arabic', meaning: 'Trustworthy', popularity: 285 },
  { name: 'Anahi', slug: 'anahi-2', gender: 'girl', origin: 'Persian', meaning: 'Immortal', popularity: 398 },
  { name: 'Anika', slug: 'anika-2', gender: 'girl', origin: 'Sanskrit', meaning: 'Grace', popularity: 425 },
  { name: 'Antonella', slug: 'antonella', gender: 'girl', origin: 'Italian', meaning: 'Priceless', popularity: 345 },
  { name: 'Ari', slug: 'ari-girl', gender: 'girl', origin: 'Hebrew', meaning: 'Lion', popularity: 398 },
  { name: 'Ariyah', slug: 'ariyah', gender: 'girl', origin: 'Hebrew', meaning: 'Lioness of God', popularity: 312 },
  { name: 'Armani', slug: 'armani-girl', gender: 'girl', origin: 'Italian', meaning: 'Warrior', popularity: 425 },
  { name: 'Astrid', slug: 'astrid-2', gender: 'girl', origin: 'Norse', meaning: 'Divine strength', popularity: 398 },
  { name: 'Athena', slug: 'athena-2', gender: 'girl', origin: 'Greek', meaning: 'Goddess of wisdom', popularity: 185 },
  { name: 'Baylor', slug: 'baylor', gender: 'girl', origin: 'English', meaning: 'Deliverer', popularity: 512 },
  { name: 'Berkley', slug: 'berkley', gender: 'girl', origin: 'English', meaning: 'Birch meadow', popularity: 485 },
  { name: 'Billie', slug: 'billie', gender: 'girl', origin: 'German', meaning: 'Resolute protector', popularity: 312 },
  { name: 'Blake', slug: 'blake-girl-2', gender: 'girl', origin: 'English', meaning: 'Dark, fair', popularity: 385 },
  { name: 'Blakely', slug: 'blakely-2', gender: 'girl', origin: 'English', meaning: 'Dark meadow', popularity: 298 },
  { name: 'Braelynn', slug: 'braelynn', gender: 'girl', origin: 'American', meaning: 'Combination name', popularity: 385 },
  { name: 'Briella', slug: 'briella', gender: 'girl', origin: 'Italian', meaning: 'God is my strength', popularity: 185 },
  { name: 'Brynlee', slug: 'brynlee-2', gender: 'girl', origin: 'Welsh', meaning: 'Hill meadow', popularity: 225 },
  { name: 'Calliope', slug: 'calliope', gender: 'girl', origin: 'Greek', meaning: 'Beautiful voice', popularity: 398 },
  { name: 'Cameron', slug: 'cameron-girl-2', gender: 'girl', origin: 'Scottish', meaning: 'Crooked nose', popularity: 345 },
  { name: 'Celine', slug: 'celine', gender: 'girl', origin: 'French', meaning: 'Heavenly', popularity: 385 },
  { name: 'Charley', slug: 'charley-2', gender: 'girl', origin: 'German', meaning: 'Free woman', popularity: 312 },
  { name: 'Collins', slug: 'collins-girl', gender: 'girl', origin: 'Irish', meaning: 'Holly', popularity: 385 },
  { name: 'Dani', slug: 'dani', gender: 'girl', origin: 'Hebrew', meaning: 'God is my judge', popularity: 485 },
  { name: 'Davina', slug: 'davina-2', gender: 'girl', origin: 'Hebrew', meaning: 'Beloved', popularity: 485 },
  { name: 'Dylan', slug: 'dylan-girl', gender: 'girl', origin: 'Welsh', meaning: 'Son of the sea', popularity: 398 },
  { name: 'Eileen', slug: 'eileen-2', gender: 'girl', origin: 'Irish', meaning: 'Light', popularity: 485 },
  { name: 'Elise', slug: 'elise-2', gender: 'girl', origin: 'French', meaning: 'Pledged to God', popularity: 312 },
  { name: 'Elliott', slug: 'elliott-girl', gender: 'girl', origin: 'Hebrew', meaning: 'The Lord is my God', popularity: 345 },
  { name: 'Ellis', slug: 'ellis-girl-2', gender: 'girl', origin: 'Welsh', meaning: 'Benevolent', popularity: 425 },
  { name: 'Emberly', slug: 'emberly', gender: 'girl', origin: 'English', meaning: 'Spark', popularity: 385 },
  { name: 'Emmeline', slug: 'emmeline-2', gender: 'girl', origin: 'German', meaning: 'Hardworking', popularity: 485 },
  { name: 'Emory', slug: 'emory', gender: 'girl', origin: 'German', meaning: 'Brave, powerful', popularity: 285 },
  { name: 'Estella', slug: 'estella-2', gender: 'girl', origin: 'Latin', meaning: 'Star', popularity: 398 },
  { name: 'Esther', slug: 'esther-2', gender: 'girl', origin: 'Persian', meaning: 'Star', popularity: 312 },
  { name: 'Everlee', slug: 'everlee-2', gender: 'girl', origin: 'English', meaning: 'Wild boar meadow', popularity: 298 },
  { name: 'Fatima', slug: 'fatima-2', gender: 'girl', origin: 'Arabic', meaning: 'Captivating', popularity: 285 },
  { name: 'Fernanda', slug: 'fernanda-2', gender: 'girl', origin: 'Spanish', meaning: 'Adventurous', popularity: 425 },
  { name: 'Freya', slug: 'freya-2', gender: 'girl', origin: 'Norse', meaning: 'Noble woman', popularity: 185 },
  { name: 'Gabriela', slug: 'gabriela', gender: 'girl', origin: 'Spanish', meaning: 'God is my strength', popularity: 145 },
];

const finalBoyNames = [
  { name: 'Sylas', slug: 'sylas', gender: 'boy', origin: 'Latin', meaning: 'Forest', popularity: 285 },
  { name: 'Tanner', slug: 'tanner', gender: 'boy', origin: 'English', meaning: 'Leather worker', popularity: 345 },
  { name: 'Tate', slug: 'tate', gender: 'boy', origin: 'English', meaning: 'Cheerful', popularity: 285 },
  { name: 'Taylor', slug: 'taylor-boy', gender: 'boy', origin: 'English', meaning: 'Tailor', popularity: 285 },
  { name: 'Terrance', slug: 'terrance', gender: 'boy', origin: 'Latin', meaning: 'Tender', popularity: 512 },
  { name: 'Terry', slug: 'terry-boy', gender: 'boy', origin: 'German', meaning: 'Power of the tribe', popularity: 485 },
  { name: 'Thaddeus', slug: 'thaddeus', gender: 'boy', origin: 'Aramaic', meaning: 'Courageous heart', popularity: 485 },
  { name: 'Theo', slug: 'theo', gender: 'boy', origin: 'Greek', meaning: 'Divine gift', popularity: 105 },
  { name: 'Theodore', slug: 'theodore', gender: 'boy', origin: 'Greek', meaning: 'Divine gift', popularity: 8 },
  { name: 'Thiago', slug: 'thiago', gender: 'boy', origin: 'Spanish', meaning: 'Supplanter', popularity: 85 },
  { name: 'Thomas', slug: 'thomas', gender: 'boy', origin: 'Aramaic', meaning: 'Twin', popularity: 48 },
  { name: 'Timothy', slug: 'timothy', gender: 'boy', origin: 'Greek', meaning: 'Honoring God', popularity: 178 },
  { name: 'Titan', slug: 'titan', gender: 'boy', origin: 'Greek', meaning: 'Defender', popularity: 385 },
  { name: 'Titus', slug: 'titus', gender: 'boy', origin: 'Latin', meaning: 'Title of honor', popularity: 285 },
  { name: 'Tobias', slug: 'tobias', gender: 'boy', origin: 'Hebrew', meaning: 'God is good', popularity: 145 },
  { name: 'Tomas', slug: 'tomas', gender: 'boy', origin: 'Aramaic', meaning: 'Twin', popularity: 385 },
  { name: 'Tommy', slug: 'tommy', gender: 'boy', origin: 'Aramaic', meaning: 'Twin', popularity: 485 },
  { name: 'Tony', slug: 'tony', gender: 'boy', origin: 'Latin', meaning: 'Priceless', popularity: 385 },
  { name: 'Trace', slug: 'trace', gender: 'boy', origin: 'French', meaning: 'Brave', popularity: 485 },
  { name: 'Travis', slug: 'travis', gender: 'boy', origin: 'French', meaning: 'Tollgate keeper', popularity: 385 },
  { name: 'Trent', slug: 'trent', gender: 'boy', origin: 'English', meaning: 'Gushing waters', popularity: 485 },
  { name: 'Trenton', slug: 'trenton', gender: 'boy', origin: 'English', meaning: 'Trent\'s town', popularity: 385 },
  { name: 'Trevor', slug: 'trevor', gender: 'boy', origin: 'Welsh', meaning: 'Great settlement', popularity: 312 },
  { name: 'Trey', slug: 'trey', gender: 'boy', origin: 'English', meaning: 'Three', popularity: 285 },
  { name: 'Tripp', slug: 'tripp', gender: 'boy', origin: 'English', meaning: 'Traveler', popularity: 385 },
  { name: 'Tristan', slug: 'tristan', gender: 'boy', origin: 'Celtic', meaning: 'Tumult', popularity: 145 },
  { name: 'Troy', slug: 'troy', gender: 'boy', origin: 'Irish', meaning: 'Foot soldier', popularity: 385 },
  { name: 'Truett', slug: 'truett', gender: 'boy', origin: 'English', meaning: 'Little honest one', popularity: 425 },
  { name: 'Tucker', slug: 'tucker', gender: 'boy', origin: 'English', meaning: 'Fabric pleater', popularity: 225 },
  { name: 'Turner', slug: 'turner', gender: 'boy', origin: 'English', meaning: 'Lathe worker', popularity: 512 },
  { name: 'Tyler', slug: 'tyler', gender: 'boy', origin: 'English', meaning: 'Tile maker', popularity: 125 },
  { name: 'Tyson', slug: 'tyson', gender: 'boy', origin: 'French', meaning: 'Firebrand', popularity: 285 },
  { name: 'Ulises', slug: 'ulises', gender: 'boy', origin: 'Latin', meaning: 'Wrathful', popularity: 485 },
  { name: 'Uriah', slug: 'uriah', gender: 'boy', origin: 'Hebrew', meaning: 'My light is Jehovah', popularity: 385 },
  { name: 'Uriel', slug: 'uriel', gender: 'boy', origin: 'Hebrew', meaning: 'God is my light', popularity: 285 },
  { name: 'Valentino', slug: 'valentino', gender: 'boy', origin: 'Italian', meaning: 'Strength, health', popularity: 385 },
  { name: 'Van', slug: 'van', gender: 'boy', origin: 'Dutch', meaning: 'Of', popularity: 485 },
  { name: 'Vance', slug: 'vance', gender: 'boy', origin: 'English', meaning: 'Marshland', popularity: 512 },
  { name: 'Vernon', slug: 'vernon', gender: 'boy', origin: 'French', meaning: 'Alder tree', popularity: 512 },
  { name: 'Vicente', slug: 'vicente', gender: 'boy', origin: 'Spanish', meaning: 'Conquering', popularity: 385 },
  { name: 'Victor', slug: 'victor', gender: 'boy', origin: 'Latin', meaning: 'Winner', popularity: 178 },
  { name: 'Vihaan', slug: 'vihaan', gender: 'boy', origin: 'Sanskrit', meaning: 'Dawn', popularity: 385 },
  { name: 'Vincent', slug: 'vincent', gender: 'boy', origin: 'Latin', meaning: 'Conquering', popularity: 125 },
  { name: 'Vincenzo', slug: 'vincenzo', gender: 'boy', origin: 'Italian', meaning: 'Conquering', popularity: 385 },
  { name: 'Waylon', slug: 'waylon', gender: 'boy', origin: 'English', meaning: 'Land by the road', popularity: 85 },
  { name: 'Wade', slug: 'wade', gender: 'boy', origin: 'English', meaning: 'River crossing', popularity: 345 },
  { name: 'Walker', slug: 'walker', gender: 'boy', origin: 'English', meaning: 'Cloth walker', popularity: 145 },
  { name: 'Wallace', slug: 'wallace', gender: 'boy', origin: 'Scottish', meaning: 'Foreigner', popularity: 512 },
  { name: 'Walter', slug: 'walter', gender: 'boy', origin: 'German', meaning: 'Army ruler', popularity: 345 },
  { name: 'Warren', slug: 'warren', gender: 'boy', origin: 'German', meaning: 'Park keeper', popularity: 385 },
  { name: 'Watson', slug: 'watson', gender: 'boy', origin: 'English', meaning: 'Son of Walter', popularity: 385 },
  { name: 'Wayne', slug: 'wayne', gender: 'boy', origin: 'English', meaning: 'Wagon maker', popularity: 485 },
  { name: 'Wells', slug: 'wells', gender: 'boy', origin: 'English', meaning: 'Spring', popularity: 385 },
  { name: 'Wesley', slug: 'wesley', gender: 'boy', origin: 'English', meaning: 'Western meadow', popularity: 85 },
  { name: 'Weston', slug: 'weston', gender: 'boy', origin: 'English', meaning: 'Western town', popularity: 145 },
  { name: 'Wilder', slug: 'wilder', gender: 'boy', origin: 'English', meaning: 'Untamed', popularity: 225 },
  { name: 'Wilhelm', slug: 'wilhelm', gender: 'boy', origin: 'German', meaning: 'Resolute protector', popularity: 512 },
  { name: 'Will', slug: 'will', gender: 'boy', origin: 'German', meaning: 'Resolute protector', popularity: 285 },
  { name: 'William', slug: 'william', gender: 'boy', origin: 'German', meaning: 'Resolute protector', popularity: 7 },
  { name: 'Wilson', slug: 'wilson', gender: 'boy', origin: 'English', meaning: 'Son of Will', popularity: 385 },
  { name: 'Winston', slug: 'winston', gender: 'boy', origin: 'English', meaning: 'Wine\'s town', popularity: 285 },
  { name: 'Wyatt', slug: 'wyatt', gender: 'boy', origin: 'English', meaning: 'Brave in war', popularity: 32 },
  { name: 'Xander', slug: 'xander', gender: 'boy', origin: 'Greek', meaning: 'Defender of the people', popularity: 178 },
  { name: 'Xavier', slug: 'xavier', gender: 'boy', origin: 'Basque', meaning: 'New house', popularity: 85 },
  { name: 'Yahir', slug: 'yahir', gender: 'boy', origin: 'Hebrew', meaning: 'He will enlighten', popularity: 385 },
  { name: 'Yosef', slug: 'yosef', gender: 'boy', origin: 'Hebrew', meaning: 'God will increase', popularity: 485 },
  { name: 'Zachariah', slug: 'zachariah', gender: 'boy', origin: 'Hebrew', meaning: 'God has remembered', popularity: 385 },
  { name: 'Zachary', slug: 'zachary', gender: 'boy', origin: 'Hebrew', meaning: 'God has remembered', popularity: 145 },
  { name: 'Zain', slug: 'zain', gender: 'boy', origin: 'Arabic', meaning: 'Beauty, grace', popularity: 385 },
  { name: 'Zander', slug: 'zander', gender: 'boy', origin: 'Greek', meaning: 'Defender of men', popularity: 285 },
  { name: 'Zane', slug: 'zane', gender: 'boy', origin: 'Hebrew', meaning: 'God is gracious', popularity: 178 },
  { name: 'Zayd', slug: 'zayd', gender: 'boy', origin: 'Arabic', meaning: 'Growth', popularity: 385 },
  { name: 'Zayne', slug: 'zayne', gender: 'boy', origin: 'Hebrew', meaning: 'God is gracious', popularity: 285 },
  { name: 'Zechariah', slug: 'zechariah', gender: 'boy', origin: 'Hebrew', meaning: 'God has remembered', popularity: 285 },
  { name: 'Zeke', slug: 'zeke', gender: 'boy', origin: 'Hebrew', meaning: 'God strengthens', popularity: 385 },
  { name: 'Zion', slug: 'zion-boy', gender: 'boy', origin: 'Hebrew', meaning: 'Highest point', popularity: 125 },
  { name: 'Zyaire', slug: 'zyaire', gender: 'boy', origin: 'American', meaning: 'River', popularity: 385 },
];

const finalUnisexNames = [
  { name: 'Arden', slug: 'arden', gender: 'unisex', origin: 'English', meaning: 'Valley of the eagle', popularity: 385 },
  { name: 'Asa', slug: 'asa', gender: 'unisex', origin: 'Hebrew', meaning: 'Healer', popularity: 345 },
  { name: 'Atlas', slug: 'atlas-unisex', gender: 'unisex', origin: 'Greek', meaning: 'To carry', popularity: 225 },
  { name: 'August', slug: 'august-unisex-2', gender: 'unisex', origin: 'Latin', meaning: 'Great', popularity: 185 },
  { name: 'Bear', slug: 'bear', gender: 'unisex', origin: 'German', meaning: 'Strong, brave', popularity: 385 },
  { name: 'Blake', slug: 'blake-unisex-2', gender: 'unisex', origin: 'English', meaning: 'Dark, fair', popularity: 225 },
  { name: 'Blue', slug: 'blue', gender: 'unisex', origin: 'English', meaning: 'Color name', popularity: 485 },
  { name: 'Briar', slug: 'briar-unisex', gender: 'unisex', origin: 'English', meaning: 'Thorny patch', popularity: 285 },
  { name: 'Brook', slug: 'brook', gender: 'unisex', origin: 'English', meaning: 'Small stream', popularity: 385 },
  { name: 'Cameron', slug: 'cameron-unisex-2', gender: 'unisex', origin: 'Scottish', meaning: 'Crooked nose', popularity: 145 },
  { name: 'Carson', slug: 'carson-unisex', gender: 'unisex', origin: 'Scottish', meaning: 'Son of marsh dwellers', popularity: 145 },
  { name: 'Carter', slug: 'carter-unisex', gender: 'unisex', origin: 'English', meaning: 'Cart driver', popularity: 45 },
  { name: 'Charlie', slug: 'charlie-unisex-2', gender: 'unisex', origin: 'German', meaning: 'Free', popularity: 145 },
  { name: 'Cypress', slug: 'cypress', gender: 'unisex', origin: 'Greek', meaning: 'Evergreen tree', popularity: 485 },
  { name: 'Dakota', slug: 'dakota-unisex-2', gender: 'unisex', origin: 'Native American', meaning: 'Friend', popularity: 245 },
  { name: 'Dallas', slug: 'dallas-unisex-2', gender: 'unisex', origin: 'Scottish', meaning: 'Meadow dwelling', popularity: 245 },
  { name: 'Dylan', slug: 'dylan-unisex', gender: 'unisex', origin: 'Welsh', meaning: 'Son of the sea', popularity: 125 },
  { name: 'Eden', slug: 'eden-unisex-2', gender: 'unisex', origin: 'Hebrew', meaning: 'Paradise', popularity: 175 },
  { name: 'Elliott', slug: 'elliott-unisex', gender: 'unisex', origin: 'Hebrew', meaning: 'The Lord is my God', popularity: 185 },
  { name: 'Emerson', slug: 'emerson-unisex-2', gender: 'unisex', origin: 'English', meaning: 'Son of Emery', popularity: 165 },
  { name: 'Emery', slug: 'emery-unisex-2', gender: 'unisex', origin: 'German', meaning: 'Brave, powerful', popularity: 145 },
  { name: 'Everest', slug: 'everest', gender: 'unisex', origin: 'English', meaning: 'Dweller on the Eure River', popularity: 385 },
  { name: 'Ezra', slug: 'ezra-unisex-2', gender: 'unisex', origin: 'Hebrew', meaning: 'Helper', popularity: 75 },
  { name: 'Fallon', slug: 'fallon-unisex', gender: 'unisex', origin: 'Irish', meaning: 'Leader', popularity: 385 },
  { name: 'Finley', slug: 'finley-unisex-2', gender: 'unisex', origin: 'Irish', meaning: 'Fair warrior', popularity: 125 },
  { name: 'Gray', slug: 'gray-unisex', gender: 'unisex', origin: 'English', meaning: 'Gray-haired', popularity: 345 },
  { name: 'Harley', slug: 'harley-unisex-2', gender: 'unisex', origin: 'English', meaning: 'Hare meadow', popularity: 175 },
  { name: 'Haven', slug: 'haven-unisex', gender: 'unisex', origin: 'English', meaning: 'Safe place', popularity: 225 },
  { name: 'Honor', slug: 'honor', gender: 'unisex', origin: 'Latin', meaning: 'Dignity', popularity: 485 },
  { name: 'Indigo', slug: 'indigo', gender: 'unisex', origin: 'Greek', meaning: 'Blue dye', popularity: 425 },
  { name: 'Jude', slug: 'jude-unisex', gender: 'unisex', origin: 'Hebrew', meaning: 'Praised', popularity: 125 },
  { name: 'Kit', slug: 'kit', gender: 'unisex', origin: 'Greek', meaning: 'Bearer of Christ', popularity: 485 },
  { name: 'Landry', slug: 'landry-unisex', gender: 'unisex', origin: 'French', meaning: 'Ruler', popularity: 385 },
  { name: 'Lux', slug: 'lux', gender: 'unisex', origin: 'Latin', meaning: 'Light', popularity: 485 },
  { name: 'Micah', slug: 'micah-unisex', gender: 'unisex', origin: 'Hebrew', meaning: 'Who is like God', popularity: 125 },
  { name: 'Milan', slug: 'milan-unisex', gender: 'unisex', origin: 'Slavic', meaning: 'Gracious', popularity: 285 },
  { name: 'Navy', slug: 'navy', gender: 'unisex', origin: 'Latin', meaning: 'Fleet of ships', popularity: 485 },
  { name: 'Nico', slug: 'nico-unisex', gender: 'unisex', origin: 'Italian', meaning: 'Victory', popularity: 285 },
  { name: 'Noel', slug: 'noel-unisex', gender: 'unisex', origin: 'French', meaning: 'Christmas', popularity: 285 },
  { name: 'North', slug: 'north', gender: 'unisex', origin: 'English', meaning: 'Direction', popularity: 485 },
  { name: 'Ocean', slug: 'ocean-unisex', gender: 'unisex', origin: 'English', meaning: 'Sea', popularity: 425 },
  { name: 'Palmer', slug: 'palmer-unisex', gender: 'unisex', origin: 'English', meaning: 'Pilgrim', popularity: 385 },
  { name: 'Phoenix', slug: 'phoenix-unisex-2', gender: 'unisex', origin: 'Greek', meaning: 'Dark red', popularity: 125 },
  { name: 'Poet', slug: 'poet', gender: 'unisex', origin: 'English', meaning: 'One who writes poems', popularity: 512 },
  { name: 'Reign', slug: 'reign', gender: 'unisex', origin: 'English', meaning: 'Royal rule', popularity: 345 },
  { name: 'Remington', slug: 'remington-unisex', gender: 'unisex', origin: 'English', meaning: 'Raven town', popularity: 285 },
  { name: 'Ripley', slug: 'ripley', gender: 'unisex', origin: 'English', meaning: 'Strip of clearing', popularity: 385 },
  { name: 'Royal', slug: 'royal-unisex', gender: 'unisex', origin: 'English', meaning: 'Of the king', popularity: 345 },
  { name: 'Saylor', slug: 'saylor', gender: 'unisex', origin: 'English', meaning: 'Sailor', popularity: 285 },
  { name: 'Seven', slug: 'seven', gender: 'unisex', origin: 'English', meaning: 'Number seven', popularity: 485 },
  { name: 'Shiloh', slug: 'shiloh-unisex', gender: 'unisex', origin: 'Hebrew', meaning: 'Peaceful', popularity: 285 },
  { name: 'Sky', slug: 'sky-unisex', gender: 'unisex', origin: 'English', meaning: 'Atmosphere', popularity: 385 },
  { name: 'Story', slug: 'story', gender: 'unisex', origin: 'English', meaning: 'Tale', popularity: 485 },
  { name: 'Tate', slug: 'tate-unisex', gender: 'unisex', origin: 'English', meaning: 'Cheerful', popularity: 285 },
  { name: 'True', slug: 'true', gender: 'unisex', origin: 'English', meaning: 'Genuine', popularity: 485 },
  { name: 'West', slug: 'west', gender: 'unisex', origin: 'English', meaning: 'Western direction', popularity: 385 },
  { name: 'Wilder', slug: 'wilder-unisex', gender: 'unisex', origin: 'English', meaning: 'Untamed', popularity: 285 },
  { name: 'Wisdom', slug: 'wisdom', gender: 'unisex', origin: 'English', meaning: 'Knowledge', popularity: 512 },
  { name: 'Wren', slug: 'wren-unisex', gender: 'unisex', origin: 'English', meaning: 'Small bird', popularity: 285 },
  { name: 'Zephyr', slug: 'zephyr', gender: 'unisex', origin: 'Greek', meaning: 'West wind', popularity: 485 },
];

// Read the current data file
const dataFilePath = path.join(__dirname, '..', 'lib', 'data.ts');
let content = fs.readFileSync(dataFilePath, 'utf8');

// Find the position of "// Second expansion batch"
const insertPoint = content.indexOf('// Second expansion batch');
if (insertPoint === -1) {
  console.error('Could not find insertion point');
  process.exit(1);
}

// Prepare the new names to insert
const allNewNames = [...finalGirlNames, ...finalBoyNames, ...finalUnisexNames];
const newNamesStr = allNewNames.map(n => {
  const meaningEscaped = n.meaning.replace(/'/g, "\\'");
  return `  { name: '${n.name}', slug: '${n.slug}', gender: '${n.gender}', origin: '${n.origin}', meaning: '${meaningEscaped}', popularity: ${n.popularity} },`;
}).join('\n');

// Insert before the comment
const newContent = content.slice(0, insertPoint) + '// Final expansion batch to reach 2000+\n' + newNamesStr + '\n\n  ' + content.slice(insertPoint);

// Write the updated content
fs.writeFileSync(dataFilePath, newContent, 'utf8');

console.log(`Added ${allNewNames.length} more names to the database`);
console.log(`- Girl names: ${finalGirlNames.length}`);
console.log(`- Boy names: ${finalBoyNames.length}`);
console.log(`- Unisex names: ${finalUnisexNames.length}`);
